// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/school/common.proto

package omo_msp_school

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type OptionType int32

const (
	OptionType_Add    OptionType = 0
	OptionType_Update OptionType = 1
	OptionType_Remove OptionType = 2
	OptionType_Get    OptionType = 3
)

var OptionType_name = map[int32]string{
	0: "Add",
	1: "Update",
	2: "Remove",
	3: "Get",
}

var OptionType_value = map[string]int32{
	"Add":    0,
	"Update": 1,
	"Remove": 2,
	"Get":    3,
}

func (x OptionType) String() string {
	return proto.EnumName(OptionType_name, int32(x))
}

func (OptionType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{0}
}

type TargetType int32

const (
	TargetType_TSelf       TargetType = 0
	TargetType_TStudent    TargetType = 1
	TargetType_TTeacher    TargetType = 2
	TargetType_TClass      TargetType = 3
	TargetType_TStudent_GH TargetType = 4
	TargetType_TTeacher_GH TargetType = 5
	TargetType_TSubject    TargetType = 6
)

var TargetType_name = map[int32]string{
	0: "TSelf",
	1: "TStudent",
	2: "TTeacher",
	3: "TClass",
	4: "TStudent_GH",
	5: "TTeacher_GH",
	6: "TSubject",
}

var TargetType_value = map[string]int32{
	"TSelf":       0,
	"TStudent":    1,
	"TTeacher":    2,
	"TClass":      3,
	"TStudent_GH": 4,
	"TTeacher_GH": 5,
	"TSubject":    6,
}

func (x TargetType) String() string {
	return proto.EnumName(TargetType_name, int32(x))
}

func (TargetType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{1}
}

type PairInfo struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairInfo) Reset()         { *m = PairInfo{} }
func (m *PairInfo) String() string { return proto.CompactTextString(m) }
func (*PairInfo) ProtoMessage()    {}
func (*PairInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{0}
}

func (m *PairInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairInfo.Unmarshal(m, b)
}
func (m *PairInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairInfo.Marshal(b, m, deterministic)
}
func (m *PairInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairInfo.Merge(m, src)
}
func (m *PairInfo) XXX_Size() int {
	return xxx_messageInfo_PairInfo.Size(m)
}
func (m *PairInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PairInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PairInfo proto.InternalMessageInfo

func (m *PairInfo) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PairInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type RequestInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Parent               string   `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestInfo) Reset()         { *m = RequestInfo{} }
func (m *RequestInfo) String() string { return proto.CompactTextString(m) }
func (*RequestInfo) ProtoMessage()    {}
func (*RequestInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{1}
}

func (m *RequestInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestInfo.Unmarshal(m, b)
}
func (m *RequestInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestInfo.Marshal(b, m, deterministic)
}
func (m *RequestInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestInfo.Merge(m, src)
}
func (m *RequestInfo) XXX_Size() int {
	return xxx_messageInfo_RequestInfo.Size(m)
}
func (m *RequestInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RequestInfo proto.InternalMessageInfo

func (m *RequestInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestInfo) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *RequestInfo) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestInfo) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

type RequestPage struct {
	Page                 uint32   `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32   `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Parent               string   `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
	Params               string   `protobuf:"bytes,6,opt,name=params,proto3" json:"params,omitempty"`
	Uid                  string   `protobuf:"bytes,7,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []string `protobuf:"bytes,8,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestPage) Reset()         { *m = RequestPage{} }
func (m *RequestPage) String() string { return proto.CompactTextString(m) }
func (*RequestPage) ProtoMessage()    {}
func (*RequestPage) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{2}
}

func (m *RequestPage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestPage.Unmarshal(m, b)
}
func (m *RequestPage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestPage.Marshal(b, m, deterministic)
}
func (m *RequestPage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestPage.Merge(m, src)
}
func (m *RequestPage) XXX_Size() int {
	return xxx_messageInfo_RequestPage.Size(m)
}
func (m *RequestPage) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestPage.DiscardUnknown(m)
}

var xxx_messageInfo_RequestPage proto.InternalMessageInfo

func (m *RequestPage) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *RequestPage) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *RequestPage) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *RequestPage) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *RequestPage) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestPage) GetParams() string {
	if m != nil {
		return m.Params
	}
	return ""
}

func (m *RequestPage) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestPage) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type RequestState struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Flag                 string   `protobuf:"bytes,2,opt,name=flag,proto3" json:"flag,omitempty"`
	State                uint32   `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestState) Reset()         { *m = RequestState{} }
func (m *RequestState) String() string { return proto.CompactTextString(m) }
func (*RequestState) ProtoMessage()    {}
func (*RequestState) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{3}
}

func (m *RequestState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestState.Unmarshal(m, b)
}
func (m *RequestState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestState.Marshal(b, m, deterministic)
}
func (m *RequestState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestState.Merge(m, src)
}
func (m *RequestState) XXX_Size() int {
	return xxx_messageInfo_RequestState.Size(m)
}
func (m *RequestState) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestState.DiscardUnknown(m)
}

var xxx_messageInfo_RequestState proto.InternalMessageInfo

func (m *RequestState) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestState) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *RequestState) GetState() uint32 {
	if m != nil {
		return m.State
	}
	return 0
}

func (m *RequestState) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type RequestList struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []string `protobuf:"bytes,4,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestList) Reset()         { *m = RequestList{} }
func (m *RequestList) String() string { return proto.CompactTextString(m) }
func (*RequestList) ProtoMessage()    {}
func (*RequestList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{4}
}

func (m *RequestList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestList.Unmarshal(m, b)
}
func (m *RequestList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestList.Marshal(b, m, deterministic)
}
func (m *RequestList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestList.Merge(m, src)
}
func (m *RequestList) XXX_Size() int {
	return xxx_messageInfo_RequestList.Size(m)
}
func (m *RequestList) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestList.DiscardUnknown(m)
}

var xxx_messageInfo_RequestList proto.InternalMessageInfo

func (m *RequestList) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *RequestList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *RequestList) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *RequestList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyStatus struct {
	Code                 uint32   `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyStatus) Reset()         { *m = ReplyStatus{} }
func (m *ReplyStatus) String() string { return proto.CompactTextString(m) }
func (*ReplyStatus) ProtoMessage()    {}
func (*ReplyStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{5}
}

func (m *ReplyStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatus.Unmarshal(m, b)
}
func (m *ReplyStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatus.Marshal(b, m, deterministic)
}
func (m *ReplyStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatus.Merge(m, src)
}
func (m *ReplyStatus) XXX_Size() int {
	return xxx_messageInfo_ReplyStatus.Size(m)
}
func (m *ReplyStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatus.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatus proto.InternalMessageInfo

func (m *ReplyStatus) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *ReplyStatus) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

type ReplyInfo struct {
	Uid                  string       `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyInfo) Reset()         { *m = ReplyInfo{} }
func (m *ReplyInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyInfo) ProtoMessage()    {}
func (*ReplyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{6}
}

func (m *ReplyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyInfo.Unmarshal(m, b)
}
func (m *ReplyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyInfo.Marshal(b, m, deterministic)
}
func (m *ReplyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyInfo.Merge(m, src)
}
func (m *ReplyInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyInfo.Size(m)
}
func (m *ReplyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyInfo proto.InternalMessageInfo

func (m *ReplyInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyList struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Uid                  string       `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	List                 []string     `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyList) Reset()         { *m = ReplyList{} }
func (m *ReplyList) String() string { return proto.CompactTextString(m) }
func (*ReplyList) ProtoMessage()    {}
func (*ReplyList) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{7}
}

func (m *ReplyList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyList.Unmarshal(m, b)
}
func (m *ReplyList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyList.Marshal(b, m, deterministic)
}
func (m *ReplyList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyList.Merge(m, src)
}
func (m *ReplyList) XXX_Size() int {
	return xxx_messageInfo_ReplyList.Size(m)
}
func (m *ReplyList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyList proto.InternalMessageInfo

func (m *ReplyList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyList) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyList) GetList() []string {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyStatistic struct {
	Status               *ReplyStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Key                  string       `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Owner                string       `protobuf:"bytes,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Count                uint32       `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStatistic) Reset()         { *m = ReplyStatistic{} }
func (m *ReplyStatistic) String() string { return proto.CompactTextString(m) }
func (*ReplyStatistic) ProtoMessage()    {}
func (*ReplyStatistic) Descriptor() ([]byte, []int) {
	return fileDescriptor_b102dd72cb6e728a, []int{8}
}

func (m *ReplyStatistic) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStatistic.Unmarshal(m, b)
}
func (m *ReplyStatistic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStatistic.Marshal(b, m, deterministic)
}
func (m *ReplyStatistic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStatistic.Merge(m, src)
}
func (m *ReplyStatistic) XXX_Size() int {
	return xxx_messageInfo_ReplyStatistic.Size(m)
}
func (m *ReplyStatistic) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStatistic.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStatistic proto.InternalMessageInfo

func (m *ReplyStatistic) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStatistic) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *ReplyStatistic) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReplyStatistic) GetCount() uint32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterEnum("omo.msp.school.OptionType", OptionType_name, OptionType_value)
	proto.RegisterEnum("omo.msp.school.TargetType", TargetType_name, TargetType_value)
	proto.RegisterType((*PairInfo)(nil), "omo.msp.school.PairInfo")
	proto.RegisterType((*RequestInfo)(nil), "omo.msp.school.RequestInfo")
	proto.RegisterType((*RequestPage)(nil), "omo.msp.school.RequestPage")
	proto.RegisterType((*RequestState)(nil), "omo.msp.school.RequestState")
	proto.RegisterType((*RequestList)(nil), "omo.msp.school.RequestList")
	proto.RegisterType((*ReplyStatus)(nil), "omo.msp.school.ReplyStatus")
	proto.RegisterType((*ReplyInfo)(nil), "omo.msp.school.ReplyInfo")
	proto.RegisterType((*ReplyList)(nil), "omo.msp.school.ReplyList")
	proto.RegisterType((*ReplyStatistic)(nil), "omo.msp.school.ReplyStatistic")
}

func init() {
	proto.RegisterFile("proto/school/common.proto", fileDescriptor_b102dd72cb6e728a)
}

var fileDescriptor_b102dd72cb6e728a = []byte{
	// 540 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x54, 0x41, 0x6f, 0xd3, 0x4c,
	0x10, 0xad, 0x63, 0xc7, 0x4d, 0x26, 0x4d, 0xbf, 0xd5, 0xea, 0x13, 0x32, 0x54, 0x48, 0x95, 0x4f,
	0x55, 0x0f, 0xa9, 0xd4, 0x48, 0x5c, 0x38, 0x01, 0x87, 0x82, 0x84, 0x44, 0xe5, 0x98, 0x0b, 0x97,
	0x68, 0x63, 0x4f, 0x52, 0x83, 0xd7, 0x6b, 0xbc, 0xeb, 0xa2, 0x1c, 0x11, 0xbf, 0x8b, 0xff, 0x86,
	0x76, 0xbd, 0x76, 0x6c, 0xd4, 0x4a, 0x08, 0x71, 0x9b, 0x37, 0x3b, 0x6f, 0xde, 0x9b, 0xd9, 0xb5,
	0xe1, 0x69, 0x59, 0x09, 0x25, 0xae, 0x64, 0x72, 0x27, 0x44, 0x7e, 0x95, 0x08, 0xce, 0x45, 0xb1,
	0x30, 0x39, 0x7a, 0x2a, 0xb8, 0x58, 0x70, 0x59, 0x2e, 0x9a, 0xc3, 0xf0, 0x1a, 0x26, 0xb7, 0x2c,
	0xab, 0xde, 0x15, 0x5b, 0x41, 0x09, 0xb8, 0x5f, 0x70, 0x1f, 0x38, 0xe7, 0xce, 0xc5, 0x34, 0xd2,
	0x21, 0xfd, 0x1f, 0xc6, 0xf7, 0x2c, 0xaf, 0x31, 0x18, 0x99, 0x5c, 0x03, 0xc2, 0xef, 0x0e, 0xcc,
	0x22, 0xfc, 0x5a, 0xa3, 0x54, 0x2d, 0xaf, 0xce, 0xd2, 0x96, 0x57, 0x67, 0x29, 0x7d, 0x06, 0x13,
	0x51, 0x62, 0xc5, 0x94, 0xa8, 0x2c, 0xb5, 0xc3, 0xf4, 0x09, 0xf8, 0xdb, 0x2c, 0x57, 0x58, 0x05,
	0xae, 0x39, 0xb1, 0xe8, 0xa0, 0xe5, 0xf5, 0xb4, 0x74, 0x75, 0xc9, 0x2a, 0x2c, 0x54, 0x30, 0x6e,
	0xaa, 0x1b, 0x14, 0xfe, 0x3c, 0x78, 0xb8, 0x65, 0x3b, 0xa4, 0x14, 0xbc, 0x92, 0xed, 0xd0, 0x98,
	0x98, 0x47, 0x26, 0xd6, 0xdc, 0xa2, 0xe6, 0x1b, 0x6c, 0x3c, 0xcc, 0x23, 0x8b, 0xfe, 0x8d, 0x03,
	0x9b, 0x67, 0x5c, 0x06, 0x7e, 0x97, 0x67, 0x5c, 0xb6, 0xdb, 0x38, 0x3e, 0x6c, 0x83, 0x82, 0x97,
	0x67, 0x52, 0x05, 0x93, 0x73, 0xf7, 0x62, 0x1a, 0x99, 0x38, 0xcc, 0xe1, 0xc4, 0xda, 0x5f, 0x29,
	0xa6, 0xfa, 0x2a, 0xce, 0x40, 0x85, 0x82, 0xb7, 0xcd, 0xd9, 0xce, 0x6e, 0xd1, 0xc4, 0xda, 0xa7,
	0xd4, 0x24, 0x63, 0x7f, 0x1e, 0x35, 0x60, 0xb0, 0x73, 0x6f, 0xb8, 0xf3, 0x70, 0xd7, 0x2d, 0xeb,
	0x7d, 0x26, 0xd5, 0xa3, 0x62, 0xd6, 0xfa, 0xe8, 0xe1, 0x8b, 0x74, 0x7f, 0xbb, 0xc8, 0x76, 0x2c,
	0xaf, 0x37, 0xd6, 0x52, 0x0b, 0x95, 0xf9, 0x5e, 0x0f, 0x55, 0x4b, 0x5d, 0x92, 0x88, 0xb4, 0xbb,
	0x15, 0x1d, 0x6b, 0x11, 0x2e, 0xdb, 0x81, 0x74, 0x18, 0x46, 0x30, 0x35, 0xa4, 0x47, 0x1e, 0xd3,
	0x12, 0x7c, 0x69, 0xda, 0x19, 0xce, 0xec, 0xfa, 0x6c, 0x31, 0x7c, 0xc3, 0x8b, 0x9e, 0x62, 0x64,
	0x4b, 0xc3, 0xad, 0xed, 0x69, 0xe6, 0x3d, 0x74, 0x70, 0xfe, 0xb8, 0xc3, 0x03, 0xcb, 0x68, 0x07,
	0x76, 0x7b, 0x03, 0xff, 0x70, 0xe0, 0xb4, 0x63, 0x67, 0x52, 0x65, 0xc9, 0x5f, 0xab, 0xe9, 0x6f,
	0x6f, 0x34, 0xf8, 0xf6, 0xc4, 0xb7, 0xa2, 0x7b, 0xa4, 0x0d, 0xd0, 0xd9, 0x44, 0xd4, 0x85, 0x32,
	0x57, 0x3c, 0x8f, 0x1a, 0x70, 0xf9, 0x02, 0xe0, 0x43, 0xa9, 0x32, 0x51, 0xc4, 0xfb, 0x12, 0xe9,
	0x31, 0xb8, 0xaf, 0xd2, 0x94, 0x1c, 0x51, 0x00, 0xff, 0x63, 0x99, 0x32, 0x85, 0xc4, 0xd1, 0x71,
	0x84, 0x5c, 0xdc, 0x23, 0x19, 0xe9, 0x82, 0x1b, 0x54, 0xc4, 0xbd, 0x14, 0x00, 0x31, 0xab, 0x76,
	0xa8, 0x0c, 0x6f, 0x0a, 0xe3, 0x78, 0x85, 0xf9, 0x96, 0x1c, 0xd1, 0x13, 0x98, 0xc4, 0x2b, 0x55,
	0xa7, 0x58, 0x28, 0xe2, 0x18, 0x14, 0x23, 0x4b, 0xee, 0xb0, 0x22, 0x23, 0xdd, 0x29, 0x7e, 0x93,
	0x33, 0x29, 0x89, 0x4b, 0xff, 0x83, 0x59, 0x5b, 0xb7, 0xbe, 0x79, 0x4b, 0x3c, 0x93, 0xb0, 0xa5,
	0x3a, 0x31, 0x6e, 0x3a, 0xd5, 0x9b, 0xcf, 0x98, 0x28, 0xe2, 0xbf, 0x7e, 0xfe, 0xe9, 0xac, 0xff,
	0x6f, 0x7a, 0x29, 0xb8, 0x58, 0x73, 0x59, 0xae, 0x1b, 0xb8, 0xf1, 0xcd, 0xe1, 0xf2, 0x57, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x67, 0xb2, 0x4f, 0x44, 0xc1, 0x04, 0x00, 0x00,
}
