// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/school/lesson.proto

package omo_msp_school

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LessonInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Scene                string   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	Created              uint64   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64   `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,9,opt,name=remark,proto3" json:"remark,omitempty"`
	Cover                string   `protobuf:"bytes,10,opt,name=cover,proto3" json:"cover,omitempty"`
	Weight               uint32   `protobuf:"varint,11,opt,name=weight,proto3" json:"weight,omitempty"`
	Tags                 []string `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets               []string `protobuf:"bytes,22,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LessonInfo) Reset()         { *m = LessonInfo{} }
func (m *LessonInfo) String() string { return proto.CompactTextString(m) }
func (*LessonInfo) ProtoMessage()    {}
func (*LessonInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_800c6d9030911218, []int{0}
}

func (m *LessonInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LessonInfo.Unmarshal(m, b)
}
func (m *LessonInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LessonInfo.Marshal(b, m, deterministic)
}
func (m *LessonInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LessonInfo.Merge(m, src)
}
func (m *LessonInfo) XXX_Size() int {
	return xxx_messageInfo_LessonInfo.Size(m)
}
func (m *LessonInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LessonInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LessonInfo proto.InternalMessageInfo

func (m *LessonInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *LessonInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LessonInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *LessonInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *LessonInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *LessonInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *LessonInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *LessonInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *LessonInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *LessonInfo) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *LessonInfo) GetWeight() uint32 {
	if m != nil {
		return m.Weight
	}
	return 0
}

func (m *LessonInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *LessonInfo) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReqLessonAdd struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Cover                string   `protobuf:"bytes,4,opt,name=cover,proto3" json:"cover,omitempty"`
	Remark               string   `protobuf:"bytes,5,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,6,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Assets               []string `protobuf:"bytes,22,rep,name=assets,proto3" json:"assets,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLessonAdd) Reset()         { *m = ReqLessonAdd{} }
func (m *ReqLessonAdd) String() string { return proto.CompactTextString(m) }
func (*ReqLessonAdd) ProtoMessage()    {}
func (*ReqLessonAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_800c6d9030911218, []int{1}
}

func (m *ReqLessonAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLessonAdd.Unmarshal(m, b)
}
func (m *ReqLessonAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLessonAdd.Marshal(b, m, deterministic)
}
func (m *ReqLessonAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLessonAdd.Merge(m, src)
}
func (m *ReqLessonAdd) XXX_Size() int {
	return xxx_messageInfo_ReqLessonAdd.Size(m)
}
func (m *ReqLessonAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLessonAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLessonAdd proto.InternalMessageInfo

func (m *ReqLessonAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqLessonAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLessonAdd) GetCover() string {
	if m != nil {
		return m.Cover
	}
	return ""
}

func (m *ReqLessonAdd) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqLessonAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqLessonAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqLessonAdd) GetAssets() []string {
	if m != nil {
		return m.Assets
	}
	return nil
}

type ReqLessonUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Tags                 []string `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLessonUpdate) Reset()         { *m = ReqLessonUpdate{} }
func (m *ReqLessonUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqLessonUpdate) ProtoMessage()    {}
func (*ReqLessonUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_800c6d9030911218, []int{2}
}

func (m *ReqLessonUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLessonUpdate.Unmarshal(m, b)
}
func (m *ReqLessonUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLessonUpdate.Marshal(b, m, deterministic)
}
func (m *ReqLessonUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLessonUpdate.Merge(m, src)
}
func (m *ReqLessonUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqLessonUpdate.Size(m)
}
func (m *ReqLessonUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLessonUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLessonUpdate proto.InternalMessageInfo

func (m *ReqLessonUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqLessonUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqLessonUpdate) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *ReqLessonUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqLessonUpdate) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

type ReplyLessonInfo struct {
	Info                 *LessonInfo  `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Role                 uint32       `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyLessonInfo) Reset()         { *m = ReplyLessonInfo{} }
func (m *ReplyLessonInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyLessonInfo) ProtoMessage()    {}
func (*ReplyLessonInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_800c6d9030911218, []int{3}
}

func (m *ReplyLessonInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLessonInfo.Unmarshal(m, b)
}
func (m *ReplyLessonInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLessonInfo.Marshal(b, m, deterministic)
}
func (m *ReplyLessonInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLessonInfo.Merge(m, src)
}
func (m *ReplyLessonInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyLessonInfo.Size(m)
}
func (m *ReplyLessonInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLessonInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLessonInfo proto.InternalMessageInfo

func (m *ReplyLessonInfo) GetInfo() *LessonInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyLessonInfo) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *ReplyLessonInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyLessonList struct {
	Total                uint32        `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 uint32        `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32        `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Number               uint32        `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus  `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*LessonInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyLessonList) Reset()         { *m = ReplyLessonList{} }
func (m *ReplyLessonList) String() string { return proto.CompactTextString(m) }
func (*ReplyLessonList) ProtoMessage()    {}
func (*ReplyLessonList) Descriptor() ([]byte, []int) {
	return fileDescriptor_800c6d9030911218, []int{4}
}

func (m *ReplyLessonList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyLessonList.Unmarshal(m, b)
}
func (m *ReplyLessonList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyLessonList.Marshal(b, m, deterministic)
}
func (m *ReplyLessonList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyLessonList.Merge(m, src)
}
func (m *ReplyLessonList) XXX_Size() int {
	return xxx_messageInfo_ReplyLessonList.Size(m)
}
func (m *ReplyLessonList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyLessonList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyLessonList proto.InternalMessageInfo

func (m *ReplyLessonList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyLessonList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyLessonList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyLessonList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyLessonList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyLessonList) GetList() []*LessonInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*LessonInfo)(nil), "omo.msp.school.LessonInfo")
	proto.RegisterType((*ReqLessonAdd)(nil), "omo.msp.school.ReqLessonAdd")
	proto.RegisterType((*ReqLessonUpdate)(nil), "omo.msp.school.ReqLessonUpdate")
	proto.RegisterType((*ReplyLessonInfo)(nil), "omo.msp.school.ReplyLessonInfo")
	proto.RegisterType((*ReplyLessonList)(nil), "omo.msp.school.ReplyLessonList")
}

func init() {
	proto.RegisterFile("proto/school/lesson.proto", fileDescriptor_800c6d9030911218)
}

var fileDescriptor_800c6d9030911218 = []byte{
	// 599 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x41, 0x4f, 0xdb, 0x30,
	0x14, 0xc7, 0x49, 0x93, 0x06, 0xea, 0x12, 0x36, 0x59, 0x1b, 0x32, 0x65, 0x1b, 0x55, 0x4e, 0x3d,
	0x05, 0xa9, 0x1c, 0x77, 0x02, 0x69, 0xeb, 0x90, 0x98, 0x98, 0x52, 0xed, 0xb2, 0x0b, 0x0a, 0x89,
	0x29, 0xd1, 0x92, 0x38, 0xc4, 0x6e, 0x27, 0x4e, 0xbb, 0xef, 0x9b, 0xec, 0xb2, 0xd3, 0x3e, 0xc7,
	0x3e, 0xd3, 0xf4, 0x9e, 0x93, 0x34, 0x85, 0x96, 0xf6, 0xc0, 0x09, 0xff, 0xfd, 0xfe, 0xfe, 0xfb,
	0x97, 0xf7, 0x8c, 0x4a, 0x0e, 0xf2, 0x42, 0x28, 0x71, 0x2c, 0xc3, 0x5b, 0x21, 0x92, 0xe3, 0x84,
	0x4b, 0x29, 0x32, 0x0f, 0xf7, 0xe8, 0x9e, 0x48, 0x85, 0x97, 0xca, 0xdc, 0xd3, 0xc5, 0xde, 0xa2,
	0x35, 0x14, 0x69, 0x5a, 0x59, 0xdd, 0xbf, 0x2d, 0x42, 0x2e, 0xf0, 0xec, 0x79, 0x76, 0x23, 0xe8,
	0x1e, 0x69, 0xc5, 0x11, 0x33, 0xfa, 0xc6, 0xc0, 0xf2, 0x5b, 0x71, 0x44, 0x5f, 0x12, 0x73, 0x1a,
	0x47, 0xac, 0xd5, 0x37, 0x06, 0x1d, 0x1f, 0x96, 0xf4, 0x15, 0x69, 0xcb, 0x90, 0x67, 0x9c, 0x99,
	0xb8, 0xa7, 0x05, 0x65, 0x64, 0x3b, 0x2c, 0x78, 0xa0, 0x78, 0xc4, 0x2c, 0x3c, 0x5c, 0x49, 0xa8,
	0x4c, 0xf3, 0x08, 0x2b, 0x6d, 0x5d, 0x29, 0x65, 0x7d, 0x46, 0x14, 0xcc, 0xc6, 0xac, 0x4a, 0xd2,
	0x1e, 0xd9, 0x11, 0x39, 0x2f, 0xb0, 0xb4, 0x8d, 0xa5, 0x5a, 0x53, 0x4a, 0xac, 0x2c, 0x48, 0x39,
	0xdb, 0xc1, 0x7d, 0x5c, 0xd3, 0x7d, 0x62, 0x17, 0x3c, 0x0d, 0x8a, 0xef, 0xac, 0x83, 0xbb, 0xa5,
	0x02, 0xd6, 0x50, 0xcc, 0x78, 0xc1, 0x88, 0x66, 0x45, 0x01, 0xee, 0x1f, 0x3c, 0x9e, 0xdc, 0x2a,
	0xd6, 0xed, 0x1b, 0x03, 0xc7, 0x2f, 0x15, 0x24, 0xab, 0x60, 0x22, 0xd9, 0xeb, 0xbe, 0x09, 0xc9,
	0xb0, 0x06, 0x6f, 0x20, 0x25, 0x57, 0x92, 0xed, 0xe3, 0x6e, 0xa9, 0xdc, 0x3f, 0x06, 0xd9, 0xf5,
	0xf9, 0x9d, 0xee, 0xdc, 0x69, 0xd4, 0x68, 0x8b, 0xd1, 0x6c, 0x4b, 0x05, 0x6b, 0x36, 0x60, 0x6b,
	0x28, 0xeb, 0x01, 0x54, 0xf9, 0x09, 0xed, 0x85, 0x4f, 0x68, 0xb6, 0xc2, 0x7e, 0xdc, 0x8a, 0x8d,
	0x81, 0x7f, 0x92, 0x17, 0x35, 0xef, 0x57, 0x1c, 0x40, 0x35, 0x5b, 0x63, 0x3e, 0xdb, 0x0a, 0xb7,
	0xb5, 0xb4, 0xb7, 0xe6, 0x4a, 0x30, 0x6b, 0x3d, 0x98, 0xfb, 0xcb, 0x00, 0x82, 0x3c, 0xb9, 0x6f,
	0xbc, 0x36, 0x8f, 0x58, 0x71, 0x76, 0x23, 0x10, 0xa1, 0x3b, 0xec, 0x79, 0x8b, 0xcf, 0xd6, 0x9b,
	0x3b, 0x7d, 0xf4, 0x41, 0x6e, 0x21, 0x12, 0xcd, 0xe7, 0xf8, 0xb8, 0xa6, 0x27, 0xc4, 0x96, 0x2a,
	0x50, 0x53, 0x89, 0x7c, 0xdd, 0xe1, 0xe1, 0xc3, 0x14, 0xbc, 0x74, 0x8c, 0x16, 0xbf, 0xb4, 0xba,
	0xff, 0x16, 0x61, 0x2e, 0x62, 0xa9, 0x60, 0x2e, 0x4a, 0xa8, 0x20, 0x41, 0x1a, 0xc7, 0xd7, 0x02,
	0xae, 0xcc, 0x83, 0x49, 0x7d, 0x25, 0xac, 0xc1, 0x09, 0x7f, 0xf5, 0x8d, 0x8e, 0xaf, 0x05, 0x34,
	0x2a, 0x9b, 0xa6, 0xd7, 0xe5, 0x60, 0x1d, 0xbf, 0x54, 0x0d, 0xc0, 0xf6, 0xc6, 0x80, 0xd0, 0x99,
	0x24, 0x96, 0xf0, 0x42, 0xcd, 0x75, 0x9d, 0x01, 0xdf, 0xf0, 0xb7, 0x45, 0x1c, 0xbd, 0x39, 0xe6,
	0xc5, 0x2c, 0x0e, 0x39, 0x3d, 0x27, 0xf6, 0x69, 0x14, 0x5d, 0x66, 0x9c, 0xbe, 0x79, 0x7c, 0xe1,
	0xfc, 0xe1, 0xf6, 0x8e, 0x96, 0xe2, 0xcc, 0x2f, 0x70, 0xb7, 0xe8, 0x27, 0x62, 0x8f, 0xb8, 0x82,
	0xa8, 0x25, 0xec, 0x77, 0x53, 0x2e, 0x15, 0x18, 0x37, 0x49, 0xfa, 0x4c, 0xba, 0x23, 0xae, 0xce,
	0xee, 0x3f, 0xc6, 0x89, 0xe2, 0xc5, 0xca, 0xb8, 0x2f, 0xc1, 0x84, 0x3f, 0x19, 0x07, 0x03, 0xd3,
	0x71, 0xe3, 0xe7, 0x88, 0xab, 0xe9, 0x76, 0x47, 0x5c, 0xc1, 0x24, 0x62, 0xa9, 0xe2, 0xf0, 0xe9,
	0xbc, 0x77, 0x2b, 0xc7, 0x88, 0x87, 0xdd, 0x2d, 0x7a, 0x49, 0x3a, 0xfa, 0x3f, 0x0d, 0x3a, 0x77,
	0xb4, 0x72, 0x08, 0xda, 0xb3, 0x09, 0xdf, 0x07, 0xd2, 0xf1, 0x79, 0x2a, 0x66, 0x7c, 0xed, 0x28,
	0x0e, 0x96, 0x86, 0xe9, 0x98, 0xb3, 0xb7, 0xdf, 0x0e, 0x9b, 0xbf, 0x07, 0xef, 0x45, 0x2a, 0xae,
	0x52, 0x99, 0x5f, 0x69, 0x79, 0x6d, 0x63, 0xf1, 0xe4, 0x7f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xcd,
	0x4b, 0xa7, 0xf3, 0x60, 0x06, 0x00, 0x00,
}
