// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/school/schedule.proto

package omo_msp_school

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ScheduleInfo struct {
	Id                   uint64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Scene                string   `protobuf:"bytes,3,opt,name=scene,proto3" json:"scene,omitempty"`
	Created              uint64   `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64   `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string   `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string   `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Name                 string   `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	Lesson               uint32   `protobuf:"varint,9,opt,name=lesson,proto3" json:"lesson,omitempty"`
	Place                string   `protobuf:"bytes,10,opt,name=place,proto3" json:"place,omitempty"`
	Date                 string   `protobuf:"bytes,11,opt,name=date,proto3" json:"date,omitempty"`
	Times                string   `protobuf:"bytes,12,opt,name=times,proto3" json:"times,omitempty"`
	Status               uint32   `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Max                  uint32   `protobuf:"varint,14,opt,name=max,proto3" json:"max,omitempty"`
	Min                  uint32   `protobuf:"varint,15,opt,name=min,proto3" json:"min,omitempty"`
	Teachers             []string `protobuf:"bytes,16,rep,name=teachers,proto3" json:"teachers,omitempty"`
	Tags                 []string `protobuf:"bytes,17,rep,name=tags,proto3" json:"tags,omitempty"`
	Users                []string `protobuf:"bytes,18,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ScheduleInfo) Reset()         { *m = ScheduleInfo{} }
func (m *ScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ScheduleInfo) ProtoMessage()    {}
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{0}
}

func (m *ScheduleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ScheduleInfo.Unmarshal(m, b)
}
func (m *ScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ScheduleInfo.Marshal(b, m, deterministic)
}
func (m *ScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ScheduleInfo.Merge(m, src)
}
func (m *ScheduleInfo) XXX_Size() int {
	return xxx_messageInfo_ScheduleInfo.Size(m)
}
func (m *ScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ScheduleInfo proto.InternalMessageInfo

func (m *ScheduleInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ScheduleInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ScheduleInfo) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ScheduleInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *ScheduleInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *ScheduleInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *ScheduleInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ScheduleInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ScheduleInfo) GetLesson() uint32 {
	if m != nil {
		return m.Lesson
	}
	return 0
}

func (m *ScheduleInfo) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *ScheduleInfo) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ScheduleInfo) GetTimes() string {
	if m != nil {
		return m.Times
	}
	return ""
}

func (m *ScheduleInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ScheduleInfo) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ScheduleInfo) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ScheduleInfo) GetTeachers() []string {
	if m != nil {
		return m.Teachers
	}
	return nil
}

func (m *ScheduleInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ScheduleInfo) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReqScheduleAdd struct {
	Scene                string   `protobuf:"bytes,1,opt,name=scene,proto3" json:"scene,omitempty"`
	Date                 string   `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Operator             string   `protobuf:"bytes,3,opt,name=operator,proto3" json:"operator,omitempty"`
	Lesson               string   `protobuf:"bytes,4,opt,name=lesson,proto3" json:"lesson,omitempty"`
	Place                string   `protobuf:"bytes,5,opt,name=place,proto3" json:"place,omitempty"`
	Times                string   `protobuf:"bytes,6,opt,name=times,proto3" json:"times,omitempty"`
	Max                  uint32   `protobuf:"varint,7,opt,name=max,proto3" json:"max,omitempty"`
	Min                  uint32   `protobuf:"varint,8,opt,name=min,proto3" json:"min,omitempty"`
	Tags                 []string `protobuf:"bytes,9,rep,name=tags,proto3" json:"tags,omitempty"`
	Teachers             []string `protobuf:"bytes,10,rep,name=teachers,proto3" json:"teachers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqScheduleAdd) Reset()         { *m = ReqScheduleAdd{} }
func (m *ReqScheduleAdd) String() string { return proto.CompactTextString(m) }
func (*ReqScheduleAdd) ProtoMessage()    {}
func (*ReqScheduleAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{1}
}

func (m *ReqScheduleAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqScheduleAdd.Unmarshal(m, b)
}
func (m *ReqScheduleAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqScheduleAdd.Marshal(b, m, deterministic)
}
func (m *ReqScheduleAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqScheduleAdd.Merge(m, src)
}
func (m *ReqScheduleAdd) XXX_Size() int {
	return xxx_messageInfo_ReqScheduleAdd.Size(m)
}
func (m *ReqScheduleAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqScheduleAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqScheduleAdd proto.InternalMessageInfo

func (m *ReqScheduleAdd) GetScene() string {
	if m != nil {
		return m.Scene
	}
	return ""
}

func (m *ReqScheduleAdd) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *ReqScheduleAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqScheduleAdd) GetLesson() string {
	if m != nil {
		return m.Lesson
	}
	return ""
}

func (m *ReqScheduleAdd) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *ReqScheduleAdd) GetTimes() string {
	if m != nil {
		return m.Times
	}
	return ""
}

func (m *ReqScheduleAdd) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ReqScheduleAdd) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ReqScheduleAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqScheduleAdd) GetTeachers() []string {
	if m != nil {
		return m.Teachers
	}
	return nil
}

type ReqScheduleUpdate struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Lesson               string   `protobuf:"bytes,2,opt,name=lesson,proto3" json:"lesson,omitempty"`
	Place                string   `protobuf:"bytes,3,opt,name=place,proto3" json:"place,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Times                string   `protobuf:"bytes,5,opt,name=times,proto3" json:"times,omitempty"`
	Max                  uint32   `protobuf:"varint,6,opt,name=max,proto3" json:"max,omitempty"`
	Min                  uint32   `protobuf:"varint,7,opt,name=min,proto3" json:"min,omitempty"`
	Teachers             []string `protobuf:"bytes,8,rep,name=teachers,proto3" json:"teachers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqScheduleUpdate) Reset()         { *m = ReqScheduleUpdate{} }
func (m *ReqScheduleUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqScheduleUpdate) ProtoMessage()    {}
func (*ReqScheduleUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{2}
}

func (m *ReqScheduleUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqScheduleUpdate.Unmarshal(m, b)
}
func (m *ReqScheduleUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqScheduleUpdate.Marshal(b, m, deterministic)
}
func (m *ReqScheduleUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqScheduleUpdate.Merge(m, src)
}
func (m *ReqScheduleUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqScheduleUpdate.Size(m)
}
func (m *ReqScheduleUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqScheduleUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqScheduleUpdate proto.InternalMessageInfo

func (m *ReqScheduleUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqScheduleUpdate) GetLesson() string {
	if m != nil {
		return m.Lesson
	}
	return ""
}

func (m *ReqScheduleUpdate) GetPlace() string {
	if m != nil {
		return m.Place
	}
	return ""
}

func (m *ReqScheduleUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqScheduleUpdate) GetTimes() string {
	if m != nil {
		return m.Times
	}
	return ""
}

func (m *ReqScheduleUpdate) GetMax() uint32 {
	if m != nil {
		return m.Max
	}
	return 0
}

func (m *ReqScheduleUpdate) GetMin() uint32 {
	if m != nil {
		return m.Min
	}
	return 0
}

func (m *ReqScheduleUpdate) GetTeachers() []string {
	if m != nil {
		return m.Teachers
	}
	return nil
}

type ReqScheduleUser struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	User                 string   `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqScheduleUser) Reset()         { *m = ReqScheduleUser{} }
func (m *ReqScheduleUser) String() string { return proto.CompactTextString(m) }
func (*ReqScheduleUser) ProtoMessage()    {}
func (*ReqScheduleUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{3}
}

func (m *ReqScheduleUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqScheduleUser.Unmarshal(m, b)
}
func (m *ReqScheduleUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqScheduleUser.Marshal(b, m, deterministic)
}
func (m *ReqScheduleUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqScheduleUser.Merge(m, src)
}
func (m *ReqScheduleUser) XXX_Size() int {
	return xxx_messageInfo_ReqScheduleUser.Size(m)
}
func (m *ReqScheduleUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqScheduleUser.DiscardUnknown(m)
}

var xxx_messageInfo_ReqScheduleUser proto.InternalMessageInfo

func (m *ReqScheduleUser) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReqScheduleUser) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqScheduleUser) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqScheduleUser) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReplyScheduleInfo struct {
	Info                 *ScheduleInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Role                 uint32        `protobuf:"varint,2,opt,name=role,proto3" json:"role,omitempty"`
	Status               *ReplyStatus  `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReplyScheduleInfo) Reset()         { *m = ReplyScheduleInfo{} }
func (m *ReplyScheduleInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyScheduleInfo) ProtoMessage()    {}
func (*ReplyScheduleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{4}
}

func (m *ReplyScheduleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyScheduleInfo.Unmarshal(m, b)
}
func (m *ReplyScheduleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyScheduleInfo.Marshal(b, m, deterministic)
}
func (m *ReplyScheduleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyScheduleInfo.Merge(m, src)
}
func (m *ReplyScheduleInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyScheduleInfo.Size(m)
}
func (m *ReplyScheduleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyScheduleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyScheduleInfo proto.InternalMessageInfo

func (m *ReplyScheduleInfo) GetInfo() *ScheduleInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyScheduleInfo) GetRole() uint32 {
	if m != nil {
		return m.Role
	}
	return 0
}

func (m *ReplyScheduleInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyScheduleUsers struct {
	Parent               string   `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Users                []string `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReplyScheduleUsers) Reset()         { *m = ReplyScheduleUsers{} }
func (m *ReplyScheduleUsers) String() string { return proto.CompactTextString(m) }
func (*ReplyScheduleUsers) ProtoMessage()    {}
func (*ReplyScheduleUsers) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{5}
}

func (m *ReplyScheduleUsers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyScheduleUsers.Unmarshal(m, b)
}
func (m *ReplyScheduleUsers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyScheduleUsers.Marshal(b, m, deterministic)
}
func (m *ReplyScheduleUsers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyScheduleUsers.Merge(m, src)
}
func (m *ReplyScheduleUsers) XXX_Size() int {
	return xxx_messageInfo_ReplyScheduleUsers.Size(m)
}
func (m *ReplyScheduleUsers) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyScheduleUsers.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyScheduleUsers proto.InternalMessageInfo

func (m *ReplyScheduleUsers) GetParent() string {
	if m != nil {
		return m.Parent
	}
	return ""
}

func (m *ReplyScheduleUsers) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReplyScheduleUsers) GetUsers() []string {
	if m != nil {
		return m.Users
	}
	return nil
}

type ReplyScheduleList struct {
	Total                uint32          `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 uint32          `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32          `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Number               uint32          `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	List                 []*ScheduleInfo `protobuf:"bytes,5,rep,name=list,proto3" json:"list,omitempty"`
	Status               *ReplyStatus    `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReplyScheduleList) Reset()         { *m = ReplyScheduleList{} }
func (m *ReplyScheduleList) String() string { return proto.CompactTextString(m) }
func (*ReplyScheduleList) ProtoMessage()    {}
func (*ReplyScheduleList) Descriptor() ([]byte, []int) {
	return fileDescriptor_77229269dad0adc8, []int{6}
}

func (m *ReplyScheduleList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyScheduleList.Unmarshal(m, b)
}
func (m *ReplyScheduleList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyScheduleList.Marshal(b, m, deterministic)
}
func (m *ReplyScheduleList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyScheduleList.Merge(m, src)
}
func (m *ReplyScheduleList) XXX_Size() int {
	return xxx_messageInfo_ReplyScheduleList.Size(m)
}
func (m *ReplyScheduleList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyScheduleList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyScheduleList proto.InternalMessageInfo

func (m *ReplyScheduleList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyScheduleList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyScheduleList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyScheduleList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyScheduleList) GetList() []*ScheduleInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func (m *ReplyScheduleList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*ScheduleInfo)(nil), "omo.msp.school.ScheduleInfo")
	proto.RegisterType((*ReqScheduleAdd)(nil), "omo.msp.school.ReqScheduleAdd")
	proto.RegisterType((*ReqScheduleUpdate)(nil), "omo.msp.school.ReqScheduleUpdate")
	proto.RegisterType((*ReqScheduleUser)(nil), "omo.msp.school.ReqScheduleUser")
	proto.RegisterType((*ReplyScheduleInfo)(nil), "omo.msp.school.ReplyScheduleInfo")
	proto.RegisterType((*ReplyScheduleUsers)(nil), "omo.msp.school.ReplyScheduleUsers")
	proto.RegisterType((*ReplyScheduleList)(nil), "omo.msp.school.ReplyScheduleList")
}

func init() {
	proto.RegisterFile("proto/school/schedule.proto", fileDescriptor_77229269dad0adc8)
}

var fileDescriptor_77229269dad0adc8 = []byte{
	// 763 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x4d, 0x4e, 0xdb, 0x40,
	0x14, 0xc6, 0x71, 0xe2, 0x24, 0x43, 0x12, 0x60, 0x54, 0x55, 0x43, 0x68, 0x69, 0xf0, 0x8a, 0x55,
	0x5a, 0xc1, 0xb2, 0x2b, 0x90, 0x5a, 0xd4, 0xaa, 0x88, 0xca, 0x29, 0x9b, 0x6e, 0x90, 0xb1, 0x1f,
	0xc1, 0xaa, 0xed, 0x31, 0x9e, 0x31, 0x2a, 0x97, 0xe8, 0x11, 0x7a, 0x9b, 0x5e, 0xa0, 0x77, 0xe8,
	0xb6, 0x67, 0xa8, 0xe6, 0x8d, 0x9d, 0x4c, 0x7e, 0x08, 0x54, 0x62, 0x95, 0xf9, 0xe6, 0x3d, 0x7f,
	0xfe, 0xbe, 0xef, 0xcd, 0x58, 0x21, 0x3b, 0x59, 0xce, 0x25, 0x7f, 0x2d, 0x82, 0x6b, 0xce, 0x63,
	0xf5, 0x03, 0x61, 0x11, 0xc3, 0x10, 0x77, 0x69, 0x8f, 0x27, 0x7c, 0x98, 0x88, 0x6c, 0xa8, 0xcb,
	0xfd, 0xed, 0x99, 0xe6, 0x80, 0x27, 0x09, 0x4f, 0x75, 0xab, 0xfb, 0xd3, 0x26, 0x9d, 0x51, 0xf9,
	0xf4, 0x87, 0xf4, 0x8a, 0xd3, 0x1e, 0xa9, 0x45, 0x21, 0xb3, 0x06, 0xd6, 0x7e, 0xdd, 0xab, 0x45,
	0x21, 0xdd, 0x24, 0x76, 0x11, 0x85, 0xac, 0x36, 0xb0, 0xf6, 0xdb, 0x9e, 0x5a, 0xd2, 0x67, 0xa4,
	0x21, 0x02, 0x48, 0x81, 0xd9, 0xb8, 0xa7, 0x01, 0x65, 0xa4, 0x19, 0xe4, 0xe0, 0x4b, 0x08, 0x59,
	0x1d, 0x1f, 0xae, 0xa0, 0xaa, 0x14, 0x59, 0x88, 0x95, 0x86, 0xae, 0x94, 0x70, 0xf2, 0x0c, 0xcf,
	0x99, 0x83, 0x5c, 0x15, 0xa4, 0x7d, 0xd2, 0xe2, 0x19, 0xe4, 0x58, 0x6a, 0x62, 0x69, 0x82, 0x29,
	0x25, 0xf5, 0xd4, 0x4f, 0x80, 0xb5, 0x70, 0x1f, 0xd7, 0xf4, 0x39, 0x71, 0x62, 0x10, 0x82, 0xa7,
	0xac, 0x3d, 0xb0, 0xf6, 0xbb, 0x5e, 0x89, 0x94, 0xd6, 0x2c, 0xf6, 0x03, 0x60, 0x44, 0x6b, 0x45,
	0xa0, 0x18, 0x94, 0x00, 0xb6, 0xae, 0x19, 0xd4, 0x5a, 0x75, 0xca, 0x28, 0x01, 0xc1, 0x3a, 0xba,
	0x13, 0x81, 0xe2, 0x15, 0xd2, 0x97, 0x85, 0x60, 0x5d, 0xcd, 0xab, 0x91, 0x4a, 0x25, 0xf1, 0xbf,
	0xb3, 0x1e, 0x6e, 0xaa, 0x25, 0xee, 0x44, 0x29, 0xdb, 0x28, 0x77, 0xa2, 0x54, 0x79, 0x90, 0xe0,
	0x07, 0xd7, 0x90, 0x0b, 0xb6, 0x39, 0xb0, 0x95, 0x87, 0x0a, 0x2b, 0x05, 0xd2, 0x1f, 0x0b, 0xb6,
	0x85, 0xfb, 0xb8, 0x56, 0x0a, 0x0a, 0xa1, 0x9a, 0x29, 0x6e, 0x6a, 0xe0, 0xfe, 0xb5, 0x48, 0xcf,
	0x83, 0x9b, 0x6a, 0x46, 0x47, 0xa1, 0x31, 0x00, 0xcb, 0x1c, 0x40, 0x65, 0xaa, 0x66, 0x98, 0x32,
	0x63, 0xb4, 0xe7, 0x62, 0x9c, 0x46, 0x56, 0xc7, 0xca, 0x42, 0x64, 0x0d, 0x33, 0xb2, 0x49, 0x3c,
	0x8e, 0x19, 0x4f, 0x19, 0x43, 0x73, 0x21, 0x86, 0xd6, 0x34, 0x86, 0xca, 0x6a, 0xdb, 0xb0, 0x6a,
	0x46, 0x43, 0x66, 0xa3, 0x71, 0x7f, 0x59, 0x64, 0xcb, 0x30, 0x7c, 0x8e, 0x67, 0xa5, 0x3a, 0x86,
	0xd6, 0xf4, 0x18, 0x4e, 0xf5, 0xd7, 0x96, 0xeb, 0xb7, 0x4d, 0xfd, 0x66, 0x12, 0xf5, 0xb9, 0x24,
	0x26, 0xde, 0x1a, 0x4b, 0xbc, 0x39, 0x0b, 0xde, 0x9a, 0xcb, 0x47, 0xdc, 0x9a, 0xf3, 0xf1, 0x8d,
	0x6c, 0x98, 0x36, 0x04, 0x60, 0xe4, 0x99, 0x9f, 0x43, 0x2a, 0x4b, 0x1f, 0x25, 0x5a, 0x72, 0xc7,
	0x28, 0xa9, 0xab, 0xf1, 0x97, 0x1e, 0x70, 0xbd, 0xca, 0x82, 0xfb, 0x03, 0x43, 0xcb, 0xe2, 0xbb,
	0x99, 0xbb, 0xfc, 0x86, 0xd4, 0xa3, 0xf4, 0x8a, 0xe3, 0xdb, 0xd6, 0x0f, 0x5e, 0x0c, 0x67, 0x3f,
	0x0b, 0x43, 0xb3, 0xd7, 0xc3, 0x4e, 0xf5, 0xde, 0x9c, 0xc7, 0xfa, 0x10, 0x75, 0x3d, 0x5c, 0xd3,
	0xc3, 0xc9, 0x1d, 0xb0, 0x91, 0x67, 0x67, 0x9e, 0x47, 0xbf, 0x18, 0x5b, 0xaa, 0x0b, 0xe2, 0x7e,
	0x21, 0x74, 0x46, 0x8f, 0xf2, 0x2f, 0xfe, 0x23, 0x80, 0xc9, 0x65, 0xb0, 0xcd, 0xcb, 0xf0, 0x7b,
	0xde, 0xe6, 0xa7, 0x48, 0x48, 0x9c, 0x1f, 0x97, 0x7e, 0x8c, 0xa4, 0x5d, 0x4f, 0x03, 0x65, 0x25,
	0xf3, 0xc7, 0x13, 0x2b, 0x6a, 0x8d, 0x67, 0xc3, 0x1f, 0x83, 0x76, 0xd2, 0xf5, 0x34, 0x50, 0xaa,
	0xd2, 0x22, 0xb9, 0x04, 0x1d, 0x6b, 0xd7, 0x2b, 0x91, 0x8a, 0x2f, 0x8e, 0x84, 0x64, 0x8d, 0x81,
	0xfd, 0x70, 0x7c, 0xaa, 0xd3, 0x88, 0xca, 0x79, 0x74, 0x54, 0x07, 0x7f, 0x1a, 0x64, 0xa3, 0xe2,
	0x1a, 0x41, 0x7e, 0x1b, 0x05, 0x40, 0x4f, 0x89, 0x73, 0x14, 0x86, 0x67, 0x29, 0xd0, 0xdd, 0x45,
	0x0a, 0xf3, 0x63, 0xd0, 0xdf, 0x5b, 0xfe, 0x0a, 0x43, 0x9b, 0xbb, 0x46, 0x3f, 0x12, 0xe7, 0x04,
	0xa4, 0xa2, 0x5b, 0xa2, 0xe8, 0xa6, 0x00, 0x21, 0x55, 0xe3, 0xe3, 0xb8, 0xce, 0xc8, 0xfa, 0x09,
	0xc8, 0xe3, 0xbb, 0xf7, 0x51, 0x2c, 0x21, 0xbf, 0x97, 0xf0, 0xb3, 0x3f, 0x86, 0x07, 0x08, 0xd5,
	0xf0, 0x34, 0xe1, 0xe8, 0x69, 0x08, 0x4b, 0x85, 0xa7, 0xa4, 0x73, 0x02, 0x52, 0xa5, 0x1c, 0x09,
	0x19, 0x05, 0xab, 0x19, 0x77, 0xef, 0x1d, 0x11, 0x3e, 0xec, 0xae, 0xd1, 0x11, 0x69, 0xeb, 0x8f,
	0x90, 0xca, 0x6f, 0x6f, 0xc5, 0x38, 0x74, 0xd7, 0xe3, 0x34, 0xbe, 0x23, 0x6d, 0x0f, 0x12, 0x7e,
	0x0b, 0x0f, 0x0e, 0x65, 0x7b, 0x29, 0x5d, 0x49, 0x33, 0x22, 0xe4, 0x28, 0xcb, 0x20, 0x0d, 0xf1,
	0xfb, 0xf2, 0x6a, 0x95, 0x38, 0x01, 0x79, 0xdf, 0x5d, 0x29, 0x0d, 0xef, 0xa8, 0xbb, 0x46, 0xcf,
	0x49, 0x67, 0x54, 0x5c, 0xca, 0xdc, 0x0f, 0xe4, 0x13, 0xd2, 0x1e, 0xbf, 0xfc, 0x3a, 0xf3, 0xa7,
	0xe5, 0x2d, 0x4f, 0xf8, 0x45, 0x22, 0xb2, 0x0b, 0x0d, 0x2f, 0x1d, 0x2c, 0x1e, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x91, 0xbf, 0x5a, 0xd3, 0xda, 0x08, 0x00, 0x00,
}
