// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/school/student.proto

package omo_msp_school

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CustodianInfo struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Identify             string   `protobuf:"bytes,2,opt,name=identify,proto3" json:"identify,omitempty"`
	Phones               []string `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CustodianInfo) Reset()         { *m = CustodianInfo{} }
func (m *CustodianInfo) String() string { return proto.CompactTextString(m) }
func (*CustodianInfo) ProtoMessage()    {}
func (*CustodianInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{0}
}

func (m *CustodianInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CustodianInfo.Unmarshal(m, b)
}
func (m *CustodianInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CustodianInfo.Marshal(b, m, deterministic)
}
func (m *CustodianInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CustodianInfo.Merge(m, src)
}
func (m *CustodianInfo) XXX_Size() int {
	return xxx_messageInfo_CustodianInfo.Size(m)
}
func (m *CustodianInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CustodianInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CustodianInfo proto.InternalMessageInfo

func (m *CustodianInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CustodianInfo) GetIdentify() string {
	if m != nil {
		return m.Identify
	}
	return ""
}

func (m *CustodianInfo) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

type StudentInfo struct {
	Id                   uint64           `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Created              uint64           `protobuf:"varint,4,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64           `protobuf:"varint,5,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string           `protobuf:"bytes,6,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string           `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Sn                   string           `protobuf:"bytes,8,opt,name=sn,proto3" json:"sn,omitempty"`
	Card                 string           `protobuf:"bytes,9,opt,name=card,proto3" json:"card,omitempty"`
	Sex                  uint32           `protobuf:"varint,10,opt,name=sex,proto3" json:"sex,omitempty"`
	Enrol                string           `protobuf:"bytes,11,opt,name=enrol,proto3" json:"enrol,omitempty"`
	Entity               string           `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	Sid                  string           `protobuf:"bytes,13,opt,name=sid,proto3" json:"sid,omitempty"`
	Class                string           `protobuf:"bytes,14,opt,name=class,proto3" json:"class,omitempty"`
	Status               uint32           `protobuf:"varint,15,opt,name=status,proto3" json:"status,omitempty"`
	School               string           `protobuf:"bytes,16,opt,name=school,proto3" json:"school,omitempty"`
	Number               uint32           `protobuf:"varint,17,opt,name=number,proto3" json:"number,omitempty"`
	Tags                 []string         `protobuf:"bytes,31,rep,name=tags,proto3" json:"tags,omitempty"`
	Custodians           []*CustodianInfo `protobuf:"bytes,40,rep,name=custodians,proto3" json:"custodians,omitempty"`
	Kvs                  []*PairInfo      `protobuf:"bytes,41,rep,name=kvs,proto3" json:"kvs,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *StudentInfo) Reset()         { *m = StudentInfo{} }
func (m *StudentInfo) String() string { return proto.CompactTextString(m) }
func (*StudentInfo) ProtoMessage()    {}
func (*StudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{1}
}

func (m *StudentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StudentInfo.Unmarshal(m, b)
}
func (m *StudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StudentInfo.Marshal(b, m, deterministic)
}
func (m *StudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StudentInfo.Merge(m, src)
}
func (m *StudentInfo) XXX_Size() int {
	return xxx_messageInfo_StudentInfo.Size(m)
}
func (m *StudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StudentInfo proto.InternalMessageInfo

func (m *StudentInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *StudentInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *StudentInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StudentInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *StudentInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *StudentInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *StudentInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *StudentInfo) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *StudentInfo) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *StudentInfo) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *StudentInfo) GetEnrol() string {
	if m != nil {
		return m.Enrol
	}
	return ""
}

func (m *StudentInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *StudentInfo) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *StudentInfo) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *StudentInfo) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *StudentInfo) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func (m *StudentInfo) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *StudentInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *StudentInfo) GetCustodians() []*CustodianInfo {
	if m != nil {
		return m.Custodians
	}
	return nil
}

func (m *StudentInfo) GetKvs() []*PairInfo {
	if m != nil {
		return m.Kvs
	}
	return nil
}

type ReqStudentAdd struct {
	Owner                string           `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sn                   string           `protobuf:"bytes,5,opt,name=sn,proto3" json:"sn,omitempty"`
	Card                 string           `protobuf:"bytes,6,opt,name=card,proto3" json:"card,omitempty"`
	Sex                  uint32           `protobuf:"varint,7,opt,name=sex,proto3" json:"sex,omitempty"`
	Operator             string           `protobuf:"bytes,8,opt,name=operator,proto3" json:"operator,omitempty"`
	Enrol                string           `protobuf:"bytes,9,opt,name=enrol,proto3" json:"enrol,omitempty"`
	Class                string           `protobuf:"bytes,10,opt,name=class,proto3" json:"class,omitempty"`
	Sid                  string           `protobuf:"bytes,11,opt,name=sid,proto3" json:"sid,omitempty"`
	Entity               string           `protobuf:"bytes,12,opt,name=entity,proto3" json:"entity,omitempty"`
	Status               uint32           `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	Number               uint32           `protobuf:"varint,14,opt,name=number,proto3" json:"number,omitempty"`
	Tags                 []string         `protobuf:"bytes,21,rep,name=tags,proto3" json:"tags,omitempty"`
	Custodians           []*CustodianInfo `protobuf:"bytes,31,rep,name=custodians,proto3" json:"custodians,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqStudentAdd) Reset()         { *m = ReqStudentAdd{} }
func (m *ReqStudentAdd) String() string { return proto.CompactTextString(m) }
func (*ReqStudentAdd) ProtoMessage()    {}
func (*ReqStudentAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{2}
}

func (m *ReqStudentAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStudentAdd.Unmarshal(m, b)
}
func (m *ReqStudentAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStudentAdd.Marshal(b, m, deterministic)
}
func (m *ReqStudentAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStudentAdd.Merge(m, src)
}
func (m *ReqStudentAdd) XXX_Size() int {
	return xxx_messageInfo_ReqStudentAdd.Size(m)
}
func (m *ReqStudentAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStudentAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStudentAdd proto.InternalMessageInfo

func (m *ReqStudentAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqStudentAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStudentAdd) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *ReqStudentAdd) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *ReqStudentAdd) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *ReqStudentAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStudentAdd) GetEnrol() string {
	if m != nil {
		return m.Enrol
	}
	return ""
}

func (m *ReqStudentAdd) GetClass() string {
	if m != nil {
		return m.Class
	}
	return ""
}

func (m *ReqStudentAdd) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *ReqStudentAdd) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *ReqStudentAdd) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *ReqStudentAdd) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReqStudentAdd) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *ReqStudentAdd) GetCustodians() []*CustodianInfo {
	if m != nil {
		return m.Custodians
	}
	return nil
}

type ReqStudentUpdate struct {
	Owner                string           `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid                  string           `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string           `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Card                 string           `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Sex                  uint32           `protobuf:"varint,5,opt,name=sex,proto3" json:"sex,omitempty"`
	Sn                   string           `protobuf:"bytes,6,opt,name=sn,proto3" json:"sn,omitempty"`
	Operator             string           `protobuf:"bytes,7,opt,name=operator,proto3" json:"operator,omitempty"`
	Enrol                string           `protobuf:"bytes,9,opt,name=enrol,proto3" json:"enrol,omitempty"`
	Custodians           []*CustodianInfo `protobuf:"bytes,21,rep,name=custodians,proto3" json:"custodians,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqStudentUpdate) Reset()         { *m = ReqStudentUpdate{} }
func (m *ReqStudentUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqStudentUpdate) ProtoMessage()    {}
func (*ReqStudentUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{3}
}

func (m *ReqStudentUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStudentUpdate.Unmarshal(m, b)
}
func (m *ReqStudentUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStudentUpdate.Marshal(b, m, deterministic)
}
func (m *ReqStudentUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStudentUpdate.Merge(m, src)
}
func (m *ReqStudentUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqStudentUpdate.Size(m)
}
func (m *ReqStudentUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStudentUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStudentUpdate proto.InternalMessageInfo

func (m *ReqStudentUpdate) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqStudentUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStudentUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStudentUpdate) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *ReqStudentUpdate) GetSex() uint32 {
	if m != nil {
		return m.Sex
	}
	return 0
}

func (m *ReqStudentUpdate) GetSn() string {
	if m != nil {
		return m.Sn
	}
	return ""
}

func (m *ReqStudentUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStudentUpdate) GetEnrol() string {
	if m != nil {
		return m.Enrol
	}
	return ""
}

func (m *ReqStudentUpdate) GetCustodians() []*CustodianInfo {
	if m != nil {
		return m.Custodians
	}
	return nil
}

type ReqStudentCustodian struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Identify             string   `protobuf:"bytes,4,opt,name=identify,proto3" json:"identify,omitempty"`
	Phones               string   `protobuf:"bytes,5,opt,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStudentCustodian) Reset()         { *m = ReqStudentCustodian{} }
func (m *ReqStudentCustodian) String() string { return proto.CompactTextString(m) }
func (*ReqStudentCustodian) ProtoMessage()    {}
func (*ReqStudentCustodian) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{4}
}

func (m *ReqStudentCustodian) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStudentCustodian.Unmarshal(m, b)
}
func (m *ReqStudentCustodian) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStudentCustodian.Marshal(b, m, deterministic)
}
func (m *ReqStudentCustodian) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStudentCustodian.Merge(m, src)
}
func (m *ReqStudentCustodian) XXX_Size() int {
	return xxx_messageInfo_ReqStudentCustodian.Size(m)
}
func (m *ReqStudentCustodian) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStudentCustodian.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStudentCustodian proto.InternalMessageInfo

func (m *ReqStudentCustodian) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqStudentCustodian) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStudentCustodian) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqStudentCustodian) GetIdentify() string {
	if m != nil {
		return m.Identify
	}
	return ""
}

func (m *ReqStudentCustodian) GetPhones() string {
	if m != nil {
		return m.Phones
	}
	return ""
}

type ReqStudentBind struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Entity               string   `protobuf:"bytes,2,opt,name=entity,proto3" json:"entity,omitempty"`
	Uid                  string   `protobuf:"bytes,3,opt,name=uid,proto3" json:"uid,omitempty"`
	Card                 string   `protobuf:"bytes,4,opt,name=card,proto3" json:"card,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqStudentBind) Reset()         { *m = ReqStudentBind{} }
func (m *ReqStudentBind) String() string { return proto.CompactTextString(m) }
func (*ReqStudentBind) ProtoMessage()    {}
func (*ReqStudentBind) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{5}
}

func (m *ReqStudentBind) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStudentBind.Unmarshal(m, b)
}
func (m *ReqStudentBind) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStudentBind.Marshal(b, m, deterministic)
}
func (m *ReqStudentBind) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStudentBind.Merge(m, src)
}
func (m *ReqStudentBind) XXX_Size() int {
	return xxx_messageInfo_ReqStudentBind.Size(m)
}
func (m *ReqStudentBind) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStudentBind.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStudentBind proto.InternalMessageInfo

func (m *ReqStudentBind) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqStudentBind) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *ReqStudentBind) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqStudentBind) GetCard() string {
	if m != nil {
		return m.Card
	}
	return ""
}

func (m *ReqStudentBind) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

type ReqStudentBatch struct {
	Owner                string           `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string           `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []*ReqStudentAdd `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqStudentBatch) Reset()         { *m = ReqStudentBatch{} }
func (m *ReqStudentBatch) String() string { return proto.CompactTextString(m) }
func (*ReqStudentBatch) ProtoMessage()    {}
func (*ReqStudentBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{6}
}

func (m *ReqStudentBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqStudentBatch.Unmarshal(m, b)
}
func (m *ReqStudentBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqStudentBatch.Marshal(b, m, deterministic)
}
func (m *ReqStudentBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqStudentBatch.Merge(m, src)
}
func (m *ReqStudentBatch) XXX_Size() int {
	return xxx_messageInfo_ReqStudentBatch.Size(m)
}
func (m *ReqStudentBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqStudentBatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqStudentBatch proto.InternalMessageInfo

func (m *ReqStudentBatch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqStudentBatch) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqStudentBatch) GetList() []*ReqStudentAdd {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyStudentInfo struct {
	Info                 *StudentInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyStudentInfo) Reset()         { *m = ReplyStudentInfo{} }
func (m *ReplyStudentInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyStudentInfo) ProtoMessage()    {}
func (*ReplyStudentInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{7}
}

func (m *ReplyStudentInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStudentInfo.Unmarshal(m, b)
}
func (m *ReplyStudentInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStudentInfo.Marshal(b, m, deterministic)
}
func (m *ReplyStudentInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStudentInfo.Merge(m, src)
}
func (m *ReplyStudentInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyStudentInfo.Size(m)
}
func (m *ReplyStudentInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStudentInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStudentInfo proto.InternalMessageInfo

func (m *ReplyStudentInfo) GetInfo() *StudentInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyStudentInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyStudentList struct {
	Total                uint32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page                 uint32         `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Pages                uint32         `protobuf:"varint,3,opt,name=pages,proto3" json:"pages,omitempty"`
	Number               uint32         `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*StudentInfo `protobuf:"bytes,11,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyStudentList) Reset()         { *m = ReplyStudentList{} }
func (m *ReplyStudentList) String() string { return proto.CompactTextString(m) }
func (*ReplyStudentList) ProtoMessage()    {}
func (*ReplyStudentList) Descriptor() ([]byte, []int) {
	return fileDescriptor_1f522acf3f8a748b, []int{8}
}

func (m *ReplyStudentList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyStudentList.Unmarshal(m, b)
}
func (m *ReplyStudentList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyStudentList.Marshal(b, m, deterministic)
}
func (m *ReplyStudentList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyStudentList.Merge(m, src)
}
func (m *ReplyStudentList) XXX_Size() int {
	return xxx_messageInfo_ReplyStudentList.Size(m)
}
func (m *ReplyStudentList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyStudentList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyStudentList proto.InternalMessageInfo

func (m *ReplyStudentList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyStudentList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyStudentList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyStudentList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyStudentList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyStudentList) GetList() []*StudentInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*CustodianInfo)(nil), "omo.msp.school.CustodianInfo")
	proto.RegisterType((*StudentInfo)(nil), "omo.msp.school.StudentInfo")
	proto.RegisterType((*ReqStudentAdd)(nil), "omo.msp.school.ReqStudentAdd")
	proto.RegisterType((*ReqStudentUpdate)(nil), "omo.msp.school.ReqStudentUpdate")
	proto.RegisterType((*ReqStudentCustodian)(nil), "omo.msp.school.ReqStudentCustodian")
	proto.RegisterType((*ReqStudentBind)(nil), "omo.msp.school.ReqStudentBind")
	proto.RegisterType((*ReqStudentBatch)(nil), "omo.msp.school.ReqStudentBatch")
	proto.RegisterType((*ReplyStudentInfo)(nil), "omo.msp.school.ReplyStudentInfo")
	proto.RegisterType((*ReplyStudentList)(nil), "omo.msp.school.ReplyStudentList")
}

func init() {
	proto.RegisterFile("proto/school/student.proto", fileDescriptor_1f522acf3f8a748b)
}

var fileDescriptor_1f522acf3f8a748b = []byte{
	// 937 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x8e, 0x28, 0x4a, 0x96, 0x46, 0x96, 0xec, 0xb2, 0x4d, 0xb1, 0x71, 0x9a, 0x58, 0x60, 0x2f,
	0x6a, 0x0f, 0x32, 0xea, 0x1c, 0x8b, 0x1e, 0xec, 0x22, 0x11, 0xdc, 0xb4, 0x8d, 0x4b, 0xb7, 0x28,
	0x90, 0x4b, 0xc0, 0x90, 0x6b, 0x7b, 0x51, 0x91, 0xab, 0x70, 0x57, 0x6e, 0x74, 0xeb, 0xa5, 0xef,
	0xd7, 0x07, 0xe8, 0xb1, 0xaf, 0xd0, 0x7b, 0x31, 0xb3, 0x14, 0x7f, 0x24, 0x91, 0x65, 0x90, 0x9c,
	0xb4, 0xb3, 0x3b, 0xf3, 0xed, 0xcc, 0xf7, 0xcd, 0x0e, 0x21, 0x38, 0x5a, 0x24, 0x52, 0xcb, 0x13,
	0x15, 0xdc, 0x4a, 0x39, 0x3f, 0x51, 0x7a, 0x19, 0xf2, 0x58, 0x4f, 0x69, 0xd3, 0x19, 0xc9, 0x48,
	0x4e, 0x23, 0xb5, 0x98, 0x9a, 0xd3, 0xa3, 0x07, 0x25, 0xdf, 0x40, 0x46, 0x91, 0x8c, 0x8d, 0xab,
	0xfb, 0x2b, 0x0c, 0xbf, 0x5d, 0x2a, 0x2d, 0x43, 0xe1, 0xc7, 0x17, 0xf1, 0xb5, 0x74, 0x1c, 0xb0,
	0x63, 0x3f, 0xe2, 0xac, 0x35, 0x6e, 0x4d, 0xfa, 0x1e, 0xad, 0x9d, 0x23, 0xe8, 0x09, 0x84, 0x17,
	0xd7, 0x2b, 0x66, 0xd1, 0x7e, 0x66, 0x3b, 0x9f, 0x42, 0x77, 0x71, 0x2b, 0x63, 0xae, 0x58, 0x7b,
	0xdc, 0x9e, 0xf4, 0xbd, 0xd4, 0x72, 0xff, 0xb0, 0x61, 0x70, 0x65, 0xb2, 0x22, 0xdc, 0x11, 0x58,
	0x22, 0x24, 0x54, 0xdb, 0xb3, 0x44, 0xe8, 0x1c, 0x42, 0x7b, 0x29, 0xc2, 0x14, 0x0e, 0x97, 0xd9,
	0xcd, 0xed, 0xc2, 0xcd, 0x0c, 0xf6, 0x82, 0x84, 0xfb, 0x9a, 0x87, 0xcc, 0xa6, 0xd0, 0xb5, 0x89,
	0x27, 0xcb, 0x45, 0x48, 0x27, 0x1d, 0x73, 0x92, 0x9a, 0x59, 0x8c, 0x4c, 0x58, 0x97, 0xa0, 0xd6,
	0x26, 0xd6, 0x21, 0x17, 0x3c, 0xa1, 0xa3, 0x3d, 0x53, 0xc7, 0xda, 0xc6, 0xfc, 0x54, 0xcc, 0x7a,
	0xb4, 0x6b, 0xa9, 0x18, 0xb3, 0x09, 0xfc, 0x24, 0x64, 0x7d, 0x93, 0x0d, 0xae, 0x31, 0x67, 0xc5,
	0xdf, 0x32, 0x18, 0xb7, 0x26, 0x43, 0x0f, 0x97, 0xce, 0x27, 0xd0, 0xe1, 0x71, 0x22, 0xe7, 0x6c,
	0x40, 0x6e, 0xc6, 0x40, 0x4e, 0x90, 0x1d, 0xbd, 0x62, 0xfb, 0xb4, 0x9d, 0x5a, 0x14, 0x2f, 0x42,
	0x36, 0x34, 0x35, 0x2b, 0x11, 0x62, 0x7c, 0x30, 0xf7, 0x95, 0x62, 0x23, 0x13, 0x4f, 0x06, 0xc6,
	0x2b, 0xed, 0xeb, 0xa5, 0x62, 0x07, 0x74, 0x55, 0x6a, 0xd1, 0x3e, 0x69, 0xc8, 0x0e, 0x0d, 0xae,
	0xb1, 0x70, 0x3f, 0x5e, 0x46, 0xaf, 0x79, 0xc2, 0x3e, 0x32, 0xfe, 0xc6, 0xc2, 0x1a, 0xb4, 0x7f,
	0xa3, 0xd8, 0x31, 0x29, 0x43, 0x6b, 0xe7, 0x1b, 0x80, 0x60, 0x2d, 0xb8, 0x62, 0x93, 0x71, 0x7b,
	0x32, 0x38, 0x7d, 0x34, 0x2d, 0x37, 0xcc, 0xb4, 0xd4, 0x12, 0x5e, 0x21, 0xc0, 0xf9, 0x12, 0xda,
	0xbf, 0xdd, 0x29, 0xf6, 0x05, 0xc5, 0xb1, 0xcd, 0xb8, 0x4b, 0x5f, 0x24, 0x14, 0x82, 0x4e, 0xee,
	0x3f, 0x16, 0x0c, 0x3d, 0xfe, 0x26, 0xed, 0x82, 0xb3, 0x90, 0xca, 0x95, 0xbf, 0xc7, 0x3c, 0x49,
	0xbb, 0xcb, 0x18, 0x99, 0xf0, 0x56, 0x41, 0x78, 0x23, 0x47, 0x67, 0x4b, 0x8e, 0xee, 0xb6, 0x1c,
	0x7b, 0xb9, 0x1c, 0x45, 0x81, 0x7b, 0x1b, 0x02, 0x67, 0x52, 0xf5, 0x8b, 0x52, 0x65, 0x02, 0x40,
	0x51, 0x80, 0x54, 0xa8, 0x41, 0x2e, 0x54, 0x95, 0xa4, 0xb9, 0x54, 0xc3, 0x4d, 0xa9, 0x52, 0x49,
	0x46, 0x3b, 0x25, 0xb9, 0x5f, 0x29, 0xc9, 0xf1, 0x3b, 0x4a, 0xe2, 0xfe, 0xdb, 0x82, 0xc3, 0x9c,
	0xe6, 0x5f, 0xe8, 0x15, 0x54, 0x30, 0xdd, 0xec, 0xd1, 0xad, 0xb9, 0xb6, 0xb7, 0xb9, 0xee, 0xe4,
	0x5c, 0x1b, 0x85, 0xba, 0x99, 0x42, 0x75, 0x8f, 0x6b, 0x37, 0xf7, 0xe5, 0xba, 0xef, 0xbf, 0x6b,
	0xdd, 0x7f, 0xb6, 0xe0, 0xe3, 0xbc, 0xee, 0xcc, 0xef, 0xbd, 0x4a, 0x2f, 0x4e, 0x3a, 0xbb, 0x72,
	0xd2, 0x99, 0xb6, 0xcc, 0x26, 0x5d, 0x0b, 0x46, 0x79, 0x1e, 0xe7, 0x22, 0xae, 0xea, 0xf3, 0xbc,
	0x87, 0xac, 0xcd, 0xb1, 0x80, 0xa9, 0xb5, 0x4b, 0xa9, 0x6d, 0x29, 0x50, 0xe4, 0xb7, 0x53, 0xe6,
	0xd7, 0xbd, 0x83, 0x83, 0x42, 0x06, 0xbe, 0x0e, 0x6e, 0x2b, 0x52, 0x28, 0x82, 0x58, 0x1b, 0x22,
	0x7d, 0x05, 0xf6, 0x5c, 0x28, 0xcd, 0x06, 0xbb, 0x85, 0x28, 0xbd, 0x64, 0x8f, 0x5c, 0xdd, 0xb7,
	0xd8, 0x79, 0x8b, 0xf9, 0xaa, 0x38, 0xe8, 0x4f, 0xc0, 0x16, 0xf1, 0xb5, 0xa4, 0x7b, 0x07, 0xa7,
	0x0f, 0x37, 0x61, 0x0a, 0xae, 0x1e, 0x39, 0x3a, 0x4f, 0xb2, 0x27, 0x64, 0xed, 0x0e, 0x49, 0xaf,
	0x40, 0x97, 0xf5, 0xfb, 0x72, 0xff, 0x6a, 0x95, 0xaf, 0xfe, 0x5e, 0x28, 0x8d, 0x35, 0x6b, 0xa9,
	0xfd, 0x39, 0xdd, 0x3d, 0xf4, 0x8c, 0x81, 0x64, 0x2e, 0xfc, 0x1b, 0x33, 0x5e, 0x86, 0x1e, 0xad,
	0xd1, 0x13, 0x7f, 0x15, 0x91, 0x3e, 0xf4, 0x8c, 0x51, 0x78, 0xb4, 0x76, 0xe9, 0xd1, 0xe6, 0x19,
	0x76, 0x1a, 0x67, 0x88, 0x3c, 0x14, 0xe8, 0xac, 0xe7, 0x01, 0x1d, 0x4f, 0xff, 0xee, 0xc1, 0x28,
	0xdd, 0xbd, 0xe2, 0xc9, 0x9d, 0x08, 0xb8, 0xf3, 0x1c, 0xba, 0x67, 0x61, 0xf8, 0x22, 0xe6, 0x4e,
	0xbd, 0x1c, 0x47, 0xe3, 0x8a, 0x8c, 0xb2, 0x3b, 0xdc, 0x7b, 0xce, 0x05, 0x74, 0x67, 0x5c, 0x23,
	0xd8, 0x8e, 0xfc, 0xdf, 0x2c, 0xb9, 0x22, 0xc7, 0x46, 0x50, 0x3f, 0xc2, 0x60, 0xc6, 0xf5, 0xf9,
	0xea, 0x99, 0x98, 0x6b, 0x9e, 0x54, 0xe2, 0x5d, 0xfa, 0x37, 0xbc, 0x1e, 0x0f, 0x65, 0x73, 0xef,
	0x39, 0xdf, 0xc1, 0xde, 0x8c, 0x1b, 0x0d, 0xdf, 0x1b, 0xeb, 0x39, 0xf4, 0x66, 0x5c, 0x9f, 0x25,
	0x89, 0xbf, 0xaa, 0x04, 0x43, 0xd7, 0x46, 0x60, 0x3f, 0xc0, 0xfe, 0x8c, 0x6b, 0x54, 0x56, 0x28,
	0x2d, 0x82, 0xfa, 0xec, 0x1e, 0x57, 0xb6, 0x05, 0x05, 0x1b, 0xde, 0xae, 0x3e, 0x08, 0x6f, 0xa9,
	0x0e, 0x3f, 0x41, 0xdf, 0xcc, 0x7b, 0x54, 0x75, 0x5c, 0xdd, 0x22, 0xc6, 0xa9, 0x11, 0xe4, 0x53,
	0xe8, 0x7b, 0x3c, 0x92, 0x77, 0xfc, 0x7f, 0x1b, 0xe5, 0xc1, 0x4e, 0xb4, 0x14, 0xe6, 0x05, 0xf4,
	0xce, 0xc2, 0xd0, 0x8c, 0xa2, 0xe3, 0xea, 0xc4, 0xc8, 0xa1, 0x91, 0x12, 0x97, 0x00, 0x38, 0x5a,
	0x9f, 0x9a, 0x91, 0xf9, 0xb8, 0x06, 0x52, 0xc4, 0xcd, 0xde, 0xc3, 0x4b, 0x38, 0x30, 0xbc, 0xe4,
	0x9f, 0x8e, 0xcf, 0xab, 0x61, 0x33, 0xa7, 0x46, 0xd8, 0xcf, 0x00, 0x0c, 0xf6, 0xcf, 0xf8, 0x81,
	0xaf, 0x6d, 0xc3, 0xdd, 0x34, 0xa6, 0x55, 0x5f, 0xc0, 0xbe, 0xc1, 0x31, 0xc3, 0xc5, 0xf9, 0xac,
	0x02, 0x09, 0x8f, 0x79, 0xad, 0x22, 0xe7, 0x8f, 0x5e, 0x3e, 0x2c, 0xfe, 0x0d, 0xf8, 0x5a, 0x46,
	0xf2, 0x55, 0xa4, 0x16, 0xaf, 0x8c, 0xf9, 0xba, 0x4b, 0x87, 0x4f, 0xfe, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0x14, 0x80, 0x7f, 0x7c, 0x58, 0x0c, 0x00, 0x00,
}
