// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/school/teacher.proto

package omo_msp_school

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TeacherInfo struct {
	Id                   uint64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid                  string         `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Entity               string         `protobuf:"bytes,4,opt,name=entity,proto3" json:"entity,omitempty"`
	User                 string         `protobuf:"bytes,5,opt,name=user,proto3" json:"user,omitempty"`
	Created              uint64         `protobuf:"varint,6,opt,name=created,proto3" json:"created,omitempty"`
	Updated              uint64         `protobuf:"varint,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Creator              string         `protobuf:"bytes,8,opt,name=creator,proto3" json:"creator,omitempty"`
	Operator             string         `protobuf:"bytes,9,opt,name=operator,proto3" json:"operator,omitempty"`
	Owner                string         `protobuf:"bytes,10,opt,name=owner,proto3" json:"owner,omitempty"`
	Tags                 []string       `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty"`
	Classes              []string       `protobuf:"bytes,12,rep,name=classes,proto3" json:"classes,omitempty"`
	Subjects             []string       `protobuf:"bytes,13,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Histories            []*HistoryInfo `protobuf:"bytes,14,rep,name=histories,proto3" json:"histories,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TeacherInfo) Reset()         { *m = TeacherInfo{} }
func (m *TeacherInfo) String() string { return proto.CompactTextString(m) }
func (*TeacherInfo) ProtoMessage()    {}
func (*TeacherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{0}
}

func (m *TeacherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeacherInfo.Unmarshal(m, b)
}
func (m *TeacherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeacherInfo.Marshal(b, m, deterministic)
}
func (m *TeacherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeacherInfo.Merge(m, src)
}
func (m *TeacherInfo) XXX_Size() int {
	return xxx_messageInfo_TeacherInfo.Size(m)
}
func (m *TeacherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TeacherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TeacherInfo proto.InternalMessageInfo

func (m *TeacherInfo) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *TeacherInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *TeacherInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TeacherInfo) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *TeacherInfo) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *TeacherInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

func (m *TeacherInfo) GetUpdated() uint64 {
	if m != nil {
		return m.Updated
	}
	return 0
}

func (m *TeacherInfo) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *TeacherInfo) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *TeacherInfo) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *TeacherInfo) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *TeacherInfo) GetClasses() []string {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *TeacherInfo) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *TeacherInfo) GetHistories() []*HistoryInfo {
	if m != nil {
		return m.Histories
	}
	return nil
}

type HistoryInfo struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	School               string   `protobuf:"bytes,2,opt,name=school,proto3" json:"school,omitempty"`
	Remark               string   `protobuf:"bytes,3,opt,name=remark,proto3" json:"remark,omitempty"`
	Grade                uint32   `protobuf:"varint,4,opt,name=grade,proto3" json:"grade,omitempty"`
	Class                uint32   `protobuf:"varint,5,opt,name=class,proto3" json:"class,omitempty"`
	Enrol                string   `protobuf:"bytes,6,opt,name=enrol,proto3" json:"enrol,omitempty"`
	Created              uint64   `protobuf:"varint,7,opt,name=created,proto3" json:"created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HistoryInfo) Reset()         { *m = HistoryInfo{} }
func (m *HistoryInfo) String() string { return proto.CompactTextString(m) }
func (*HistoryInfo) ProtoMessage()    {}
func (*HistoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{1}
}

func (m *HistoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HistoryInfo.Unmarshal(m, b)
}
func (m *HistoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HistoryInfo.Marshal(b, m, deterministic)
}
func (m *HistoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HistoryInfo.Merge(m, src)
}
func (m *HistoryInfo) XXX_Size() int {
	return xxx_messageInfo_HistoryInfo.Size(m)
}
func (m *HistoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_HistoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_HistoryInfo proto.InternalMessageInfo

func (m *HistoryInfo) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *HistoryInfo) GetSchool() string {
	if m != nil {
		return m.School
	}
	return ""
}

func (m *HistoryInfo) GetRemark() string {
	if m != nil {
		return m.Remark
	}
	return ""
}

func (m *HistoryInfo) GetGrade() uint32 {
	if m != nil {
		return m.Grade
	}
	return 0
}

func (m *HistoryInfo) GetClass() uint32 {
	if m != nil {
		return m.Class
	}
	return 0
}

func (m *HistoryInfo) GetEnrol() string {
	if m != nil {
		return m.Enrol
	}
	return ""
}

func (m *HistoryInfo) GetCreated() uint64 {
	if m != nil {
		return m.Created
	}
	return 0
}

type ReqTeacherAdd struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Entity               string   `protobuf:"bytes,3,opt,name=entity,proto3" json:"entity,omitempty"`
	User                 string   `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Operator             string   `protobuf:"bytes,5,opt,name=operator,proto3" json:"operator,omitempty"`
	Subjects             []string `protobuf:"bytes,6,rep,name=subjects,proto3" json:"subjects,omitempty"`
	Classes              []string `protobuf:"bytes,7,rep,name=classes,proto3" json:"classes,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeacherAdd) Reset()         { *m = ReqTeacherAdd{} }
func (m *ReqTeacherAdd) String() string { return proto.CompactTextString(m) }
func (*ReqTeacherAdd) ProtoMessage()    {}
func (*ReqTeacherAdd) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{2}
}

func (m *ReqTeacherAdd) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeacherAdd.Unmarshal(m, b)
}
func (m *ReqTeacherAdd) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeacherAdd.Marshal(b, m, deterministic)
}
func (m *ReqTeacherAdd) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeacherAdd.Merge(m, src)
}
func (m *ReqTeacherAdd) XXX_Size() int {
	return xxx_messageInfo_ReqTeacherAdd.Size(m)
}
func (m *ReqTeacherAdd) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeacherAdd.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeacherAdd proto.InternalMessageInfo

func (m *ReqTeacherAdd) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqTeacherAdd) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTeacherAdd) GetEntity() string {
	if m != nil {
		return m.Entity
	}
	return ""
}

func (m *ReqTeacherAdd) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *ReqTeacherAdd) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTeacherAdd) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

func (m *ReqTeacherAdd) GetClasses() []string {
	if m != nil {
		return m.Classes
	}
	return nil
}

type ReqTeacherUpdate struct {
	Owner                string   `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Uid                  string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Operator             string   `protobuf:"bytes,4,opt,name=operator,proto3" json:"operator,omitempty"`
	Classes              []string `protobuf:"bytes,5,rep,name=classes,proto3" json:"classes,omitempty"`
	Subjects             []string `protobuf:"bytes,6,rep,name=subjects,proto3" json:"subjects,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeacherUpdate) Reset()         { *m = ReqTeacherUpdate{} }
func (m *ReqTeacherUpdate) String() string { return proto.CompactTextString(m) }
func (*ReqTeacherUpdate) ProtoMessage()    {}
func (*ReqTeacherUpdate) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{3}
}

func (m *ReqTeacherUpdate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeacherUpdate.Unmarshal(m, b)
}
func (m *ReqTeacherUpdate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeacherUpdate.Marshal(b, m, deterministic)
}
func (m *ReqTeacherUpdate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeacherUpdate.Merge(m, src)
}
func (m *ReqTeacherUpdate) XXX_Size() int {
	return xxx_messageInfo_ReqTeacherUpdate.Size(m)
}
func (m *ReqTeacherUpdate) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeacherUpdate.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeacherUpdate proto.InternalMessageInfo

func (m *ReqTeacherUpdate) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqTeacherUpdate) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *ReqTeacherUpdate) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReqTeacherUpdate) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTeacherUpdate) GetClasses() []string {
	if m != nil {
		return m.Classes
	}
	return nil
}

func (m *ReqTeacherUpdate) GetSubjects() []string {
	if m != nil {
		return m.Subjects
	}
	return nil
}

type ReqTeacherBatch struct {
	Owner                string           `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Operator             string           `protobuf:"bytes,2,opt,name=operator,proto3" json:"operator,omitempty"`
	List                 []*ReqTeacherAdd `protobuf:"bytes,3,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *ReqTeacherBatch) Reset()         { *m = ReqTeacherBatch{} }
func (m *ReqTeacherBatch) String() string { return proto.CompactTextString(m) }
func (*ReqTeacherBatch) ProtoMessage()    {}
func (*ReqTeacherBatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{4}
}

func (m *ReqTeacherBatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeacherBatch.Unmarshal(m, b)
}
func (m *ReqTeacherBatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeacherBatch.Marshal(b, m, deterministic)
}
func (m *ReqTeacherBatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeacherBatch.Merge(m, src)
}
func (m *ReqTeacherBatch) XXX_Size() int {
	return xxx_messageInfo_ReqTeacherBatch.Size(m)
}
func (m *ReqTeacherBatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeacherBatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeacherBatch proto.InternalMessageInfo

func (m *ReqTeacherBatch) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ReqTeacherBatch) GetOperator() string {
	if m != nil {
		return m.Operator
	}
	return ""
}

func (m *ReqTeacherBatch) GetList() []*ReqTeacherAdd {
	if m != nil {
		return m.List
	}
	return nil
}

type ReplyTeacherInfo struct {
	Info                 *TeacherInfo `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Status               *ReplyStatus `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ReplyTeacherInfo) Reset()         { *m = ReplyTeacherInfo{} }
func (m *ReplyTeacherInfo) String() string { return proto.CompactTextString(m) }
func (*ReplyTeacherInfo) ProtoMessage()    {}
func (*ReplyTeacherInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{5}
}

func (m *ReplyTeacherInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTeacherInfo.Unmarshal(m, b)
}
func (m *ReplyTeacherInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTeacherInfo.Marshal(b, m, deterministic)
}
func (m *ReplyTeacherInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTeacherInfo.Merge(m, src)
}
func (m *ReplyTeacherInfo) XXX_Size() int {
	return xxx_messageInfo_ReplyTeacherInfo.Size(m)
}
func (m *ReplyTeacherInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTeacherInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTeacherInfo proto.InternalMessageInfo

func (m *ReplyTeacherInfo) GetInfo() *TeacherInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *ReplyTeacherInfo) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type ReplyTeacherList struct {
	Total                uint32         `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Pages                uint32         `protobuf:"varint,2,opt,name=pages,proto3" json:"pages,omitempty"`
	Page                 uint32         `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Number               uint32         `protobuf:"varint,4,opt,name=number,proto3" json:"number,omitempty"`
	Status               *ReplyStatus   `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	List                 []*TeacherInfo `protobuf:"bytes,6,rep,name=list,proto3" json:"list,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReplyTeacherList) Reset()         { *m = ReplyTeacherList{} }
func (m *ReplyTeacherList) String() string { return proto.CompactTextString(m) }
func (*ReplyTeacherList) ProtoMessage()    {}
func (*ReplyTeacherList) Descriptor() ([]byte, []int) {
	return fileDescriptor_93ae7c86bf27648d, []int{6}
}

func (m *ReplyTeacherList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReplyTeacherList.Unmarshal(m, b)
}
func (m *ReplyTeacherList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReplyTeacherList.Marshal(b, m, deterministic)
}
func (m *ReplyTeacherList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReplyTeacherList.Merge(m, src)
}
func (m *ReplyTeacherList) XXX_Size() int {
	return xxx_messageInfo_ReplyTeacherList.Size(m)
}
func (m *ReplyTeacherList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReplyTeacherList.DiscardUnknown(m)
}

var xxx_messageInfo_ReplyTeacherList proto.InternalMessageInfo

func (m *ReplyTeacherList) GetTotal() uint32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ReplyTeacherList) GetPages() uint32 {
	if m != nil {
		return m.Pages
	}
	return 0
}

func (m *ReplyTeacherList) GetPage() uint32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReplyTeacherList) GetNumber() uint32 {
	if m != nil {
		return m.Number
	}
	return 0
}

func (m *ReplyTeacherList) GetStatus() *ReplyStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *ReplyTeacherList) GetList() []*TeacherInfo {
	if m != nil {
		return m.List
	}
	return nil
}

func init() {
	proto.RegisterType((*TeacherInfo)(nil), "omo.msp.school.TeacherInfo")
	proto.RegisterType((*HistoryInfo)(nil), "omo.msp.school.HistoryInfo")
	proto.RegisterType((*ReqTeacherAdd)(nil), "omo.msp.school.ReqTeacherAdd")
	proto.RegisterType((*ReqTeacherUpdate)(nil), "omo.msp.school.ReqTeacherUpdate")
	proto.RegisterType((*ReqTeacherBatch)(nil), "omo.msp.school.ReqTeacherBatch")
	proto.RegisterType((*ReplyTeacherInfo)(nil), "omo.msp.school.ReplyTeacherInfo")
	proto.RegisterType((*ReplyTeacherList)(nil), "omo.msp.school.ReplyTeacherList")
}

func init() {
	proto.RegisterFile("proto/school/teacher.proto", fileDescriptor_93ae7c86bf27648d)
}

var fileDescriptor_93ae7c86bf27648d = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x36, 0xf5, 0x43, 0x49, 0x23, 0x53, 0x35, 0x88, 0xc2, 0xa0, 0x65, 0xb8, 0x15, 0x78, 0xf2,
	0x49, 0x46, 0xed, 0x53, 0xd1, 0x93, 0x0c, 0xd4, 0xaa, 0xeb, 0xb6, 0x6e, 0xd6, 0xce, 0x25, 0x17,
	0x83, 0x26, 0xc7, 0x12, 0x13, 0x91, 0x2b, 0xef, 0xae, 0x9c, 0xe8, 0x6d, 0x72, 0xcf, 0x03, 0xe4,
	0x35, 0xf2, 0x0e, 0x79, 0x85, 0x3c, 0x40, 0xb0, 0xb3, 0x94, 0x45, 0x09, 0xa4, 0x22, 0x20, 0xb9,
	0xed, 0x37, 0x33, 0x3b, 0xf3, 0xed, 0x7c, 0x9f, 0x68, 0x43, 0x77, 0x2a, 0xb8, 0xe2, 0x27, 0x32,
	0x1c, 0x73, 0x3e, 0x39, 0x51, 0x18, 0x84, 0x63, 0x14, 0x7d, 0x0a, 0xba, 0x1d, 0x9e, 0xf0, 0x7e,
	0x22, 0xa7, 0x7d, 0x93, 0xed, 0x1e, 0xac, 0xd4, 0x86, 0x3c, 0x49, 0x78, 0x6a, 0x4a, 0xfd, 0x2f,
	0x15, 0x68, 0xdf, 0x9a, 0xcb, 0x97, 0xe9, 0x03, 0x77, 0x3b, 0x50, 0x89, 0x23, 0xcf, 0xea, 0x59,
	0xc7, 0x35, 0x56, 0x89, 0x23, 0x77, 0x0f, 0xaa, 0xb3, 0x38, 0xf2, 0x2a, 0x3d, 0xeb, 0xb8, 0xc5,
	0xf4, 0xd1, 0x75, 0xa1, 0x96, 0x06, 0x09, 0x7a, 0x55, 0x0a, 0xd1, 0xd9, 0xdd, 0x07, 0x1b, 0x53,
	0x15, 0xab, 0xb9, 0x57, 0xa3, 0x68, 0x86, 0x74, 0xed, 0x4c, 0xa2, 0xf0, 0xea, 0xa6, 0x56, 0x9f,
	0x5d, 0x0f, 0x1a, 0xa1, 0xc0, 0x40, 0x61, 0xe4, 0xd9, 0x34, 0x66, 0x01, 0x75, 0x66, 0x36, 0x8d,
	0x28, 0xd3, 0x30, 0x99, 0x0c, 0x3e, 0xdf, 0xe1, 0xc2, 0x6b, 0x52, 0xab, 0x05, 0x74, 0xbb, 0xd0,
	0xe4, 0x53, 0x14, 0x94, 0x6a, 0x51, 0xea, 0x19, 0xbb, 0x3f, 0x43, 0x9d, 0xbf, 0x4d, 0x51, 0x78,
	0x40, 0x09, 0x03, 0x34, 0x27, 0x15, 0x8c, 0xa4, 0xd7, 0xee, 0x55, 0x35, 0x27, 0x7d, 0xa6, 0xfe,
	0x93, 0x40, 0x4a, 0x94, 0xde, 0x2e, 0x85, 0x17, 0x50, 0xf7, 0x97, 0xb3, 0xfb, 0xd7, 0x18, 0x2a,
	0xe9, 0x39, 0x94, 0x7a, 0xc6, 0xee, 0xef, 0xd0, 0x1a, 0xc7, 0x52, 0x71, 0x11, 0xa3, 0xf4, 0x3a,
	0xbd, 0xea, 0x71, 0xfb, 0xf4, 0xb0, 0xbf, 0xba, 0xfa, 0xfe, 0x5f, 0x54, 0x30, 0xd7, 0xbb, 0x65,
	0xcb, 0x6a, 0xff, 0x83, 0x05, 0xed, 0x5c, 0x6a, 0xb1, 0x66, 0x6b, 0xb9, 0xe6, 0x7d, 0xb0, 0x4d,
	0x8b, 0x6c, 0xf7, 0x19, 0xd2, 0x71, 0x81, 0x49, 0x20, 0xde, 0x64, 0x02, 0x64, 0x48, 0x3f, 0x76,
	0x24, 0x82, 0x08, 0x49, 0x01, 0x87, 0x19, 0xa0, 0xa3, 0xf4, 0x12, 0x52, 0xc0, 0x61, 0x06, 0xe8,
	0x28, 0xa6, 0x82, 0x4f, 0x48, 0x80, 0x16, 0x33, 0x20, 0x2f, 0x4c, 0x63, 0x45, 0x18, 0xff, 0xa3,
	0x05, 0x0e, 0xc3, 0xc7, 0xcc, 0x27, 0x83, 0x28, 0x5a, 0xae, 0xd6, 0x5a, 0x5b, 0x2d, 0x59, 0xa3,
	0x52, 0x68, 0x8d, 0x6a, 0xa1, 0x35, 0x6a, 0x39, 0x6b, 0xe4, 0xc5, 0xac, 0xaf, 0x89, 0x99, 0x17,
	0xc2, 0x5e, 0x13, 0x22, 0x27, 0x5f, 0x63, 0x45, 0x3e, 0xff, 0xbd, 0x05, 0x7b, 0x4b, 0xe6, 0x2f,
	0xc9, 0x4e, 0x25, 0xe4, 0xb7, 0x73, 0x7a, 0x9e, 0x62, 0x6d, 0x8d, 0x62, 0x8e, 0x46, 0xbd, 0xdc,
	0x45, 0x6b, 0xe4, 0xfd, 0x27, 0xf8, 0x69, 0xc9, 0xf0, 0x3c, 0x50, 0xe1, 0xb8, 0x84, 0x60, 0x7e,
	0x74, 0x65, 0x6d, 0xf4, 0x6f, 0x50, 0x9b, 0xc4, 0x52, 0x79, 0x55, 0x72, 0xe1, 0xd1, 0xba, 0x0b,
	0x57, 0xc4, 0x63, 0x54, 0xea, 0xbf, 0xd3, 0x9b, 0x99, 0x4e, 0xe6, 0xf9, 0x5f, 0xff, 0x09, 0xd4,
	0xe2, 0xf4, 0x81, 0xd3, 0xdc, 0x02, 0x33, 0xe7, 0x4a, 0x19, 0x15, 0xba, 0x67, 0x60, 0x4b, 0x15,
	0xa8, 0x99, 0x24, 0x46, 0x05, 0x57, 0x68, 0xc4, 0x0d, 0x95, 0xb0, 0xac, 0xd4, 0xff, 0x64, 0xad,
	0x8e, 0xfe, 0x27, 0x96, 0x4a, 0xbf, 0x59, 0x71, 0x15, 0x4c, 0x68, 0xb6, 0xc3, 0x0c, 0xd0, 0xd1,
	0x69, 0x30, 0x42, 0xd3, 0xde, 0x61, 0x06, 0x68, 0x61, 0xf4, 0x81, 0x84, 0x71, 0x18, 0x9d, 0xb5,
	0xcf, 0xd2, 0x59, 0x72, 0x9f, 0x39, 0xca, 0x61, 0x19, 0xca, 0x31, 0xac, 0x6f, 0xcd, 0x50, 0xef,
	0x81, 0xd6, 0x69, 0x17, 0xff, 0xa8, 0x57, 0xf6, 0xa0, 0x0b, 0x4f, 0x3f, 0xdb, 0xd0, 0xc9, 0xa2,
	0x37, 0x28, 0x9e, 0xe2, 0x10, 0xdd, 0x2b, 0xb0, 0x07, 0x51, 0x74, 0x9d, 0xa2, 0xbb, 0x59, 0x8e,
	0x6e, 0xaf, 0x90, 0x51, 0x6e, 0x86, 0xbf, 0xe3, 0x5e, 0x82, 0x3d, 0x44, 0xa5, 0x9b, 0x15, 0xf0,
	0x7f, 0x9c, 0xa1, 0x54, 0xba, 0x70, 0xab, 0x56, 0x7f, 0x43, 0x63, 0x88, 0x8a, 0x76, 0x5e, 0xd6,
	0xeb, 0xff, 0x60, 0x84, 0x9b, 0x7b, 0xe9, 0xeb, 0xfe, 0x8e, 0xfb, 0x1f, 0xb4, 0x87, 0xa8, 0xce,
	0xe7, 0x17, 0xf1, 0x44, 0xa1, 0xf8, 0xfe, 0x7e, 0x57, 0xd0, 0x1c, 0xa2, 0x1a, 0x08, 0x11, 0xcc,
	0x4b, 0x9b, 0xe9, 0xd2, 0xad, 0x9a, 0xfd, 0x0b, 0xbb, 0x43, 0x54, 0x5a, 0xd9, 0x58, 0xaa, 0x38,
	0xdc, 0xcc, 0xee, 0x97, 0x52, 0x5b, 0xd0, 0x65, 0xf3, 0xd6, 0x9b, 0x1f, 0xf2, 0xd6, 0x4c, 0x87,
	0x17, 0xd0, 0x32, 0xdf, 0x23, 0xad, 0x6a, 0xaf, 0xdc, 0x22, 0xa6, 0x68, 0xab, 0x96, 0x7f, 0x42,
	0x8b, 0x61, 0xc2, 0x9f, 0xf0, 0x9b, 0x46, 0x39, 0x28, 0xec, 0x96, 0xb5, 0xb9, 0x86, 0xe6, 0x20,
	0x8a, 0xcc, 0xa7, 0xe8, 0xd7, 0x72, 0x62, 0x54, 0xb0, 0x95, 0x12, 0x17, 0x00, 0xe6, 0x15, 0xb7,
	0xfa, 0x8f, 0xed, 0x46, 0x61, 0x8b, 0x89, 0x99, 0x3e, 0xe7, 0x47, 0xaf, 0x0e, 0xf3, 0xff, 0xc9,
	0xfc, 0xc1, 0x13, 0x7e, 0x97, 0xc8, 0xe9, 0x9d, 0x81, 0xf7, 0x36, 0x25, 0xcf, 0xbe, 0x06, 0x00,
	0x00, 0xff, 0xff, 0x8d, 0xbb, 0x0b, 0x25, 0x1b, 0x09, 0x00, 0x00,
}
